module ExpandExpandGlobal;
class Foo() {
  fun test(): String {
    "Pass\n"
  }
}

fun foo(): Foo {
  Foo()
}

module end;

module ExpandExpandGlobalA;

class Foo() {
  fun test(): String {
    "fail"
  }
}

fun foo(): Foo {
  Foo()
}

fun bar(): ExpandExpandGlobal.Foo {
  ExpandExpandGlobal.foo()
}

module end;

module ExpandExpandGlobal;

fun main(): void {
  print_raw(ExpandExpandGlobalA.bar().test())
}

module end;
