module Expand_GlobalIdentifiers2;
type RealString = String;
class Foo<T>()

module end;

module Expand_GlobalIdentifiers2M;

class String() {}

fun works(): Expand_GlobalIdentifiers2.Foo<Expand_GlobalIdentifiers2.RealString> {
  Expand_GlobalIdentifiers2.Foo()
}

fun worksToo(): Expand_GlobalIdentifiers2.Foo<.String> {
  Expand_GlobalIdentifiers2.Foo()
}

module end;

module Expand_GlobalIdentifiers2;

fun main(): void {
  print_string("Pass")
}

module end;
