module alias I = ExpandModuleAliasPatternM;

module ExpandModuleAliasPattern;

module end;

module ExpandModuleAliasPatternM;

class A()
class B(A)

module end;

module ExpandModuleAliasPattern;

fun main(): void {
  a = ExpandModuleAliasPatternM.A();
  b = ExpandModuleAliasPatternM.B(a);

  _ = a match {
  | I.A() -> void
  };

  _ = a match {
  | _x @ I.A() -> void
  };

  // This does not.
  (a, a) match {
  | (I.A(), ExpandModuleAliasPatternM.A()) -> void
  };

  b match {
  | I.B(ExpandModuleAliasPatternM.A()) -> void
  };

  (b, b) match {
  | (I.B(I.A()), ExpandModuleAliasPatternM.B(ExpandModuleAliasPatternM.A())) ->
    void
  };

  print_string("Pass")
}

module end;
