module ExpandResolveNamesA;

fun foo(): Quux {
  bar + baz() + Foo().bar() + ExpandResolveNamesFoo.baz()
}

const bar: String = "P";

fun baz(): String {
  "a"
}

class Foo() {
  fun bar(): String {
    "s"
  }
}

type Quux = String;

module end;

module ExpandResolveNamesFoo;

fun baz(): String {
  "s"
}

module end;

module ExpandResolveNames;

fun main(): void {
  print_raw(ExpandResolveNamesA.foo() + "\n")
}

module end;
