module SKFSTest;

fun getAllTests(): SortedMap<String, () ~> mutable SKFS.Context> {
  SortedMap[
    "subDir" => testSubDir,
    "lazy" => testLazy,
    "string" => testString,
    //    "union" => testUnion,
    "product" => testProduct,
    "pre" => testPre,
    "count" => testCount,
    "min" => testMin,
    "range" => testIndex,
    "runtime" => testRuntime,
    "search" => testSearch,
    "stress" => testStress,
  ]
}
