module SKFSTest;

fun getAllTests(): SortedMap<String, () ~> mutable SKFS.Context> {
  SortedMap[
    //    "aggr" => testAggregates,
    "subDir" => testSubDir,
    "lazy" => testLazy,
    "string" => testString,
    "pre" => testPre,
    "count" => testCount,
    "min" => testMin,
    "range" => testIndex,
    "runtime" => testRuntime,
    "search" => testSearch,
    "size" => testSize,
    "stress" => testStress,
    "withRegion" => testWithRegion,
  ]
}
