packages:
  - "eslint-config"
  - "tsconfig"
  - "skiplang/prelude/ts/binding"
  - "skiplang/prelude/ts/wasm"
  - "skiplang/prelude/ts/worker"
  - "skiplang/skdate/ts"
  - "skiplang/skjson/ts/binding"
  - "skiplang/skjson/ts/wasm"
  - "skipruntime-ts/core"
  - "skipruntime-ts/helpers"
  - "skipruntime-ts/wasm"
  - "skipruntime-ts/addon"
  - "skipruntime-ts/adapters/kafka"
  - "skipruntime-ts/adapters/postgres"
  - "skipruntime-ts/tests"
  - "skipruntime-ts/server"
  - "skipruntime-ts/examples"
  - "skipruntime-ts/metapackage"
  - "sql/ts"
  - "sql/ts/tests"
  - "examples/hackernews/reactive_service"
  - "examples/chatroom/reactive_service"
  - "examples/blogger/reactive_service"