module SKFSTest;

fun testMap(): mutable SKFS.Context {
  data = Array[(SKFS.IID(1), SKFS.IntFile(1)), (SKFS.IID(2), SKFS.IntFile(2))];
  SKFS.run(context ~> {
    dir1 = context.mkdir(
      SKFS.IntFile::fromFile,
      SKFS.DirName::create("/dir1/"),
      false,
      data,
    );
    dir2 = dir1.contextWriterMap(
      SKFS.IntFile::fromFile,
      context,
      SKFS.DirName::create("/dir2/"),
      (_context, writer, v) ~> writer.write(SKFS.IID(0), v),
    );
    _dir3 = dir2.contextWriterKeyValues(
      SKFS.IntFile::fromFile,
      context,
      SKFS.DirName::create("/dir3/"),
      (_context, writer, _key, v) ~> {
        writer.writeArray(SKFS.IID(1), v)
      },
    );
  });
}

fun testMap2(): mutable SKFS.Context {
  dataStr1 = Array[
    (SKFS.IID(1), SKFS.StringFile("1")),
    (SKFS.IID(2), SKFS.StringFile("2")),
  ];
  dataStr2 = Array[
    (SKFS.IID(1), SKFS.StringFile("3")),
    (SKFS.IID(2), SKFS.StringFile("4")),
  ];
  SKFS.run(context ~> {
    dirStr1 = context.mkdir(
      SKFS.StringFile::fromFile,
      SKFS.DirName::create("/dirStr1/"),
      false,
      dataStr1,
    );
    dirStr2 = context.mkdir(
      SKFS.StringFile::fromFile,
      SKFS.DirName::create("/dirStr2/"),
      false,
      dataStr2,
    );
    dir1 = dirStr1.map(
      SKFS.IntFile::fromFile,
      context,
      SKFS.DirName::create("/dir1/"),
      (v ~> SKFS.IntFile(v.value.toInt())),
    );
    dir2 = dirStr2.map(
      SKFS.IntFile::fromFile,
      context,
      SKFS.DirName::create("/dir2/"),
      (v ~> SKFS.IntFile(v.value.toInt())),
    );
    _dir3 = dir1.contextWriterKeyMap(
      SKFS.IntFile::fromFile,
      context,
      SKFS.DirName::create("/dir3/"),
      (context, writer, key, v) ~> {
        dirName = SKFS.DirName::create("/dir3/" + key + "/");
        _ = dir2.map(SKFS.IntFile::fromFile, context, dirName, (v) ~> v);
        writer.write(key, v);
      },
    );
  });
}
