/*****************************************************************************/
/* Testing the "WithRegion" construct that allows garbage collection. */
/*****************************************************************************/
module SKFSTest;

fun testWithRegion(): mutable SKFS.Context {
  l = List[1, 2, 3];
  l2 = SKFS.withRegion(() ~> {
    l.map(x -> x + 1);
  });
  acc = 0;
  for (elt in l2) {
    !acc = acc + elt;
  };
  debug(acc);
  mutable SKFS.Context{}
}
