[package]
name = "std"
version = "0.1.0"

[dependencies]
core = { path = "../core" }

[dev-dependencies]
sktest = { path = "../sktest" }

[build-dependencies]
cc = { path = "../cc" }
pkg-config = { path = "../pkg-config" }
