module RuntimeMacroThisClassName;
trait ClassName {
  macro fun className(): String {
    #thisClassName
  }
}
module end;

module RuntimeMacroThisClassNameM;
class C() uses RuntimeMacroThisClassName.ClassName {}
class .G() uses RuntimeMacroThisClassName.ClassName {}
module end;

module RuntimeMacroThisClassName;
value class V() uses ClassName {}

fun main(): void {
  print_string(RuntimeMacroThisClassNameM.C().className());
  print_string(.G().className());
  print_string(V().className());
}
module end;
