version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:20.04
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -q -y npm git make lld sqlite3 gcc gawk clang llvm
      - run:
          name: Build compiler
          command: |
            cd compiler && make install STAGE=0
      - run:
          name: Run compiler tests
          no_output_timeout: 30m
          command: |
            if ! git diff --quiet HEAD master -- compiler/
            then
              cd compiler && make test STAGE=1
            fi
      - run:
          name: Run skfs tests
          command: |
            if ! git diff --quiet HEAD master -- skfs/
            then
              cd skfs && skargo test
            fi
      - run:
          name: Run skdb tests
          command: |
            if ! git diff --quiet HEAD master -- sql/
            then
              cd sql && skargo build && make test
            fi
