version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:20.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y make clang
      - run:
          name: Build runtime
          command: |
            make build/libskip_runtime64.a
      - run:
          name: Link pre-built compiler
          command: |
            gunzip -c prebuild/preamble_and_skc_out64.ll.gz > build/preamble_and_skc_out64.ll
            clang++ -O3 build/preamble_and_skc_out64.ll build/libskip_runtime64.a -o build/skc -lrt -lpthread
      - run:
          name: Build compiler
          command: |
            cd compiler && make ../build/skc
      - run:
          name: Compiler tests
          command: |
            cd compiler/tests && make
