module SKFSTest;

fun getAllTests(): SortedMap<String, () ~> mutable SKFS.Context> {
  SortedMap[
    "subDir" => testSubDir,
    "lazy" => testLazy,
    "string" => testString,
    "pre" => testPre,
    "count" => testCount,
    "runtime" => testRuntime,
    "search" => testSearch,
    "size" => testSize,
    "stress" => testStress,
    "withRegion" => testWithRegion,
    "fixedDirTime" => testFixedDirTime,
    "changesAfter" => testChangesAfter,
    "externalPointer" => testExternalPointer,
    "createDir" => testCreateDir,
    "writeChunk" => testWriteChunk,
  ]
}
