/*****************************************************************************/
/* Testing the "WithRegion" construct that allows garbage collection. */
/*****************************************************************************/
module SKFSTest;

fun testWithRegion(): mutable SKFS.Context {
  context = mutable SKFS.Context{};
  l = List[1, 2, 3];
  l2 = SKFS.withRegion(context, (_, _) ~> {
    l.map(x -> x + 1);
  });
  acc = 0;
  for (elt in l2) {
    !acc = acc + elt;
  };
  expectEq("Test withRegion", acc, () -> 9);
  context
}
