/*****************************************************************************/
/* Test that creates a directory. */
/*****************************************************************************/

module SKFSTest;

fun testCreateDir(): mutable SKFS.Context {
  SKFS.runWithGcReturnContext(SKFS.Context{}, context ~> {
    dirName = SKFS.DirName::create("/tmp/");
    mappedDirName = SKFS.DirName::create("/tmp/mapped/");
    dir = context.mkdir(SKFS.StringFile::fromFile, dirName, false, Array[]);
    _ = dir.contextWriterKeyValues(
      SKFS.StringFile::fromFile,
      context,
      mappedDirName,
      (_context, writer, key, files) ~> {
        writer.writeArray(
          key,
          files.map(file -> {
            !file.value = file.value + "Mapped";
            file
          }),
        )
      },
    );
    SKFS.CStop(None())
  })
}
