module alias T = SKTest;

module SKFSTest;

@test
fun testDirName(): void {
  T.expectThrow(() -> _ = SKFS.DirName::create(" "));
  T.expectThrow(() -> _ = SKFS.DirName::create("??$"));
  T.expectThrow(() -> _ = SKFS.DirName::create("."));
  T.expectThrow(() -> _ = SKFS.DirName::create("//"));
  T.expectThrow(() -> _ = SKFS.DirName::create("\n"));
  T.expectThrow(() -> _ = SKFS.DirName::create("/missingTrailingSlash"));

  _ = SKFS.DirName::create("/");
  _ = SKFS.DirName::create("/1223/");
  _ = SKFS.DirName::create("/dir/");
  _ = SKFS.DirName::create("/dir1/dir2/");
}

module end;
