/*****************************************************************************/
/* Testing the "WithRegion" construct that allows garbage collection. */
/*****************************************************************************/

module alias T = SKTest;

module SKFSTest;

@test
fun testWithRegion(): void {
  context = mutable SKFS.Context{};
  l = List[1, 2, 3];
  l2 = SKFS.withRegion(context, (_, _) ~> {
    l.map(x -> x + 1);
  });
  acc = 0;
  for (elt in l2) {
    !acc = acc + elt;
  };
  T.expectEq(acc, 9, "Test withRegion")
}
