module SKFSTest;

fun testDirNameFail(str: String): void {
  expectFail(`Test DirName: '${str}'`, () -> _ = SKFS.DirName::create(str));
}

fun testDirNamePass(str: String): void {
  expectPass(`Test DirName: '${str}'`, () -> _ = SKFS.DirName::create(str));
}

fun testDirName(): void {
  testDirNameFail(" ");
  testDirNameFail("??$");
  testDirNameFail(".");
  testDirNameFail("//");
  testDirNameFail("\n");
  testDirNamePass("/");
  testDirNameFail("/missingTrailingSlash");
  testDirNamePass("/1223/");
  testDirNamePass("/dir/");
  testDirNamePass("/dir1/dir2/");
}

module end;
