/*****************************************************************************/
/* Test that creates a directory. */
/*****************************************************************************/

module SKStoreTest;

@test
fun testCreateDir(): void {
  _ = SKStore.runWithGcReturnContext(SKStore.Context{}, context ~> {
    dirName = SKStore.DirName::create("/tmp/");
    mappedDirName = SKStore.DirName::create("/tmp/mapped/");
    dir = context.mkdir(
      SKStore.IID::keyType,
      SKStore.StringFile::type,
      dirName,
      Array[],
    );
    _ = dir.map(
      SKStore.IID::keyType,
      SKStore.StringFile::type,
      context,
      mappedDirName,
      (_context, writer, key, files) ~> {
        writer.setArray(
          key,
          files.collect(Array).map(file -> {
            !file.value = file.value + "Mapped";
            file
          }),
        )
      },
    );
    SKStore.CStop(None())
  })
}
