[package]
name = "skargo"
version = "0.1.0"

[dependencies]
toml = { "path" = "../toml" }
cli = { "path" = "../cli" }
std = { "path" = "../prelude" }
semver = { "path" = "../semver" }

[[bin]]
name = "skargo"
main = "Skargo.main"
