CREATE TABLE t1 (
  id TEXT PRIMARY KEY,
  t TEXT DEFAULT CURRENT_TIMESTAMP,
  n INTEGER NULLABLE,
  v INTEGER,
  w INTEGER
);

INSERT INTO t1 (v, w) VALUES (1, -1);
INSERT INTO t1 (v, w) VALUES (2, -2);
INSERT INTO t1 (n, v, w) VALUES (5, 3, -3);

INSERT INTO t1 (v, w) SELECT v, w+10 FROM t1;

SELECT id FROM t1;
