CREATE TABLE t1 (x INTEGER, y INTEGER PRIMARY KEY);
CREATE TABLE t2 (a INTEGER, b INTEGER);

INSERT INTO t1 (x, y) VALUES (1, 1), (3, 3);
INSERT INTO t2 (a, b) VALUES (1, 2), (3, 4);

CREATE REACTIVE VIEW vv1 AS SELECT a, y FROM t1 INNER JOIN t2 on a = x;
CREATE REACTIVE VIEW vv2 AS SELECT MAX(y) FROM t1;

SELECT * FROM vv1;
SELECT * FROM vv2;

ALTER TABLE t1 ADD COLUMN z INTEGER NOT NULL DEFAULT 0;

INSERT INTO t1 (x, y) VALUES (10,10);
INSERT INTO t1 (x, y, z) VALUES (3,5,8);

SELECT * FROM vv1;
SELECT * FROM vv2;
