create table t1 (a INTEGER PRIMARY KEY, b TEXT, c TEXT default 'hello');
create table t2 (a INTEGER PRIMARY KEY, b TEXT, c TEXT not null default 'hello');
create table t3 (a INTEGER PRIMARY KEY, b TEXT, c TEXT default 'hello' not null);
create table t4 (a TEXT PRIMARY KEY, b TEXT, c TEXT default 'hello' not null);
insert into t1 (b, c) values ('test1', 'test2');
insert into t1 (a, c) values (local_sequence_number(), 'foo');
insert into t1 (a, b) values (local_sequence_number(), 'bar');
select * from t1;
insert into t4 (a, c) values (id(), 'foo');
insert into t4 (a, b) values (id(), 'bar');
select * from t4;
