module alias T = SKTest;

module SKStoreTest;

class IBox(value: Int) extends SKStore.File

fun convertIBox(file: SKStore.File): IBox {
  file match {
  | x @ IBox _ -> x
  | _ -> invariant_violation("Was expecting an IBox")
  }
}

fun convertSFile(file: SKStore.File): IBox {
  file match {
  | SKStore.StringFile(v) -> IBox(v.toInt())
  | _ -> invariant_violation("Was expecting an IBox")
  }
}

fun make(
  context: mutable SKStore.Context,
  name: String,
  values: Array<Int>,
): SKStore.EHandle<SKStore.IID, SKStore.StringFile> {
  kvArray = values.map(x -> (SKStore.IID(x), SKStore.StringFile(x.toString())));
  context.mkdir(
    SKStore.IID::keyType,
    SKStore.StringFile::type,
    SKStore.DirName::create(name),
    kvArray,
  )
}

fun compareResults(
  context: mutable SKStore.Context,
  kind: String,
  strPath: String,
  values: Array<Int>,
): void {
  path = SKStore.Path::fromString(strPath);
  dir = context.unsafeGetDir(path.dirName);
  readV = dir.getArrayRaw(path.baseName);
  try {
    T.expectEq(
      readV.map(IBox::type).map(v -> v.value),
      values,
      kind + " test for path " + strPath,
    );
  } catch {
  | _ ->
    debug(readV);
    debug(values);
    T.fail("Compare result failed\n")
  }
}

fun testUpdate(
  context: mutable SKStore.Context,
  writes: Array<(String, Array<Int>)>,
  expects: Array<(String, Array<Int>)>,
): void {
  for (kv in writes) {
    (key, values) = kv;
    path = SKStore.Path::fromString(key);
    dir = context.unsafeGetEagerDir(path.dirName);
    dir.writeArray(context, path.baseName, values.map(x -> IBox(x)));
  };
  context.update();
  for (kv in expects) {
    (key, values) = kv;
    compareResults(context, "Update", key, values);
  };
}
/*

fun testMap(): void {
  // Base case
  (context, _) = SKStore.start(context ~> {
    dir1 = make(context, "/tmp1/", Array[1, 2, 3]);
    dir2 = dir1.apply(context, "/tmp2/", (_, writer, key, values) ~> {
      writer.setArray(
        key,
        values.map(x -> {
          x match {
          | IBox(v) -> IBox(v + 1)
          | _ -> IBox(0)
          }
        }),
      )
    });
    _dir3 = dir1.apply(
      context,
      "/tmp3/",
      (context, writer, key, origValues2) ~> {
        values1 = dir2.getArray(context, key).map(convertIBox);
        values2 = origValues2.map(convertIBox);
        size = min(values1.size(), values2.size());
        result = mutable Vector[];
        for (i in Range(0, size)) {
          result.push(IBox(values1[i].value + values2[i].value));
        };
        writer.setArray(key, result.toArray());
      },
    );
    compareResults(context, "Map", "/tmp2/1", Array[2]);
    compareResults(context, "Map", "/tmp2/2", Array[3]);
    compareResults(context, "Map", "/tmp2/3", Array[4]);
  });

  testUpdate(context, Array[("/tmp1/2", Array[])], Array[("/tmp2/2", Array[])]);
  testUpdate(
    context,
    Array[("/tmp1/2", Array[22])],
    Array[("/tmp2/2", Array[23])],
  );
  context.debug("/tmp3/2");
  testUpdate(
    context,
    Array[("/tmp1/2", Array[24])],
    Array[("/tmp3/2", Array[49])],
  );
  testUpdate(context, Array[("/tmp1/2", Array[])], Array[("/tmp3/2", Array[])]);
}

fun testPartition(): void {
  (context, _) = SKStore.start(context ~> {
    dir1 = make(context, "/tmp1/", Array[1, 2, 3]);
    dir2 = dir1.apply(context, "/tmp2/", (_context, writer, _key, values) ~> {
      if (values.size() == 0) return void;
      writer.setArray(SKStore.IID(1), values);
    });
    dir3 = dir2.partition(context, "/tmp3/", x ~>
      SKStore.IID(convertIBox(x).value)
    );
    _ = dir3.apply(context, "/tmp4/", (context, writer, key, dirs) ~> {
      if (dirs.size() == 0) return void;
      dir = convertDir(dirs[0]);
      subDirName = "M" + key;
      newDirName = "/tmpMapped/" + subDirName + "/";
      newDir = dir.apply(
        context,
        newDirName,
        (_context, writer, key, iboxes) ~> {
          !iboxes = iboxes.map(origV -> {
            v = convertIBox(origV);
            !v.value = v.value + 1;
            v
          });
          writer.setArray(key, iboxes)
        },
      );
      writer.set(SKStore.SID::create(subDirName), newDir);
    });
  });
  testUpdate(
    context,
    Array[("/tmp1/1", Array[2])],
    Array[("/tmp3/1/2", Array[2, 2])],
  );

  testUpdate(
    context,
    Array[("/tmp1/1", Array[1])],
    Array[("/tmp3/1/2", Array[2]), ("/tmp3/1/1", Array[1])],
  );

  testUpdate(
    context,
    Array[("/tmp1/1", Array[])],
    Array[("/tmp3/1/2", Array[2]), ("/tmp3/1/1", Array[])],
  );
  context.debug("/tmpMapped/M1/3");
}


fun testDirs(): void {
  //  testUnion();
  // testMap();
  testPartition();
}
*/

@test
fun testSubDirUnit(): void {
  _ = SKStore.run(context ~> {
    dir1 = context.mkdir(
      SKStore.IID::keyType,
      SKStore.StringFile::type,
      SKStore.DirName::create("/dir1/"),
    );
    _dir2 = dir1.map(
      SKStore.IID::keyType,
      SKStore.StringFile::type,
      context,
      SKStore.DirName::create("/dir1/dir2/"),
      (context, writer, key, values) ~> {
        x = values.first;
        _ = dir1.map(
          SKStore.IID::keyType,
          SKStore.StringFile::type,
          context,
          SKStore.DirName::create("/dir1/dir2/" + x.value + "/"),
          (_context, writer, key, values) ~> writer.set(key, values.first),
        );
        writer.set(key, x)
      },
    );
  })
}

module end;
