[package]
name = "skmonitor"
version = "0.1.0"

[dev-dependencies]
sktest = { path = "../sktest" }

[build-dependencies]
cc = { "path" = "../cc" }

[dependencies]
std = { path = "../prelude" }

[[bin]]
name = "skmonitor"
main = "SKMonitor.main"