[package]
name = "skip-runtime-ts"
version = "0.1.0"

[dependencies]
std = { path = "../../../prelude" }
skjson = { path = "../../../skjson" }

[dev-dependencies]
sktest = { path = "../../../sktest" }

[lib]
type = ["cdylib"]
