/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

class FooBar() extends Exception

fun main(): void {
  if (arguments().any(x -> x == "--init")) {
    _ = SKFS.gContextInit(SKFS.Context{});
    return void;
  };
  SKFS.runWithGc(SKFS.Context{}, context ~> {
    _result = compile(context, kConfig.unknown);
    SKFS.CStop(None())
  })
}
