[package]
name = "skc"
version = "0.1.0"
tests = ["tests/tests.sk"]
test-harness = "SkcTests.main"

[dependencies]
std = { "path" = "../prelude" }
cli = { "path" = "../cli" }
arparser = { "path" = "../arparser" }
sktest = { "path" = "../sktest" }

[[bin]]
name = "skc"
main = "main"

[[bin]]
name = "skfmt"
main = "SkipPrinter.main"
