[package]
name = "skc"
version = "0.1.0"
tests = ["tests/tests.sk"]
test-harness = "SkcTests.main"

[dependencies]
skfs = { "path" = "../skfs" }
cli = { "path" = "../cli" }

[[bin]]
name = "skc"
main = "main"

[[bin]]
name = "skfmt"
main = "SkipPrinter.main"
