[package]
name = "sknpm"
version = "0.1.0"

[dependencies]
skargo = { "path" = "../skargo" }
skbuild = { "path" = "../skbuild" }

[build-dependencies]
skbuild = { "path" = "../skbuild" }

[[bin]]
name = "sknpm"
main = "Sknpm.main"