class E() extends Exception {
  fun getMessage(): String {
    ""
  }
}

class Ex() extends Exception {
  fun getMessage(): String {
    ""
  }
}

fun t(_e: Exception): Bool {
  false
}

fun throws(): String {
  vtry(
    () -> {
      throw E();
    },
    exn ->
      exn match {
      | e if (t(e)) -> throw Ex()
      | e -> throw e
      }
    ,
  )
}

fun main(): void {
  print_raw(
    vtry(
      () -> {
        throws()
      },
      exn ->
        exn match {
        | E() -> "Pass\n"
        | _ -> "Fail"
        }
      ,
    ),
  )
}
