services:
  # Reverse proxy
  haproxy:
    image: reactive-blogger/reverse_proxy
    build: ./reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      www:
        condition: service_healthy
      reactive_service:
        condition: service_healthy

  # Web application
  web:
    image: reactive-blogger/web-service
    build: ./web_service
    depends_on:
      db:
        condition: service_healthy

  # SQL database
  db:
    image: reactive-blogger/db
    build: ./db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Reactive service
  reactive_service:
    image: reactive-blogger/reactive-service
    build: ./reactive_service
    depends_on:
      db:
        condition: service_healthy

  # Front-end
  www:
    image: reactive-blogger/www
    build: ./www

volumes:
  pgdata:
