apiVersion: v1
kind: Service
metadata:
  name: rhn-www
  labels:
    app.kubernetes.io/name: rhn-www
spec:
  ports:
    - port: 80
      name: http
  selector:
    app.kubernetes.io/name: rhn-www
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhn-www
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rhn-www
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rhn-www
    spec:
      imagePullSecrets:
      - name: rhn-skip-ecr-registry
      containers:
      - name: rhn-www
        image: __ECR__:www
        ports:
        - containerPort: 80
