module alias A = SyntaxMultipleModuleAliasesM;
module alias B = SyntaxMultipleModuleAliasesM;

module SyntaxMultipleModuleAliases;
// comment

/* test */


// comment

/* test */


// comment

/* test */

module end;

module SyntaxMultipleModuleAliasesM;

const s: String = "s";
module end;

module SyntaxMultipleModuleAliases;

fun main(): void {
  print_raw("Pa" + A.s + B.s + "\n")
}

module end;
