CREATE VIRTUAL VIEW V0 AS SELECT ALL ( + 39 ) * 15 FROM tab1
;

CREATE VIRTUAL VIEW V1 AS SELECT DISTINCT * FROM tab2 WHERE - col2 + col1 IS NOT NULL
;

CREATE VIRTUAL VIEW V2 AS SELECT ALL + col1 AS col0, col2 AS col2 FROM tab1
;

CREATE VIRTUAL VIEW V3 AS SELECT + + col0 AS col0, col2, - + col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V4 AS SELECT - - col0, 37 + col2 AS col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V5 AS SELECT ALL - 98 AS col1 FROM tab1 cor0
;

CREATE VIRTUAL VIEW V6 AS SELECT DISTINCT * FROM tab1 AS cor0 WHERE NOT - 78 IS NOT NULL
;

CREATE VIRTUAL VIEW V7 AS SELECT ALL - - 41 + + - col2 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V8 AS SELECT ALL 4 AS col1 FROM tab2 AS cor0 WHERE NULL IS NULL
;

CREATE VIRTUAL VIEW V9 AS SELECT DISTINCT * FROM tab1 AS cor0 WHERE + 69 IS NULL
;

CREATE VIRTUAL VIEW V10 AS SELECT 38 AS col2, - col0 AS col2 FROM tab2 WHERE + col2 IS NOT NULL
;

CREATE VIRTUAL VIEW V11 AS SELECT - 30 + + 5 * - ( col1 ) FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V12 AS SELECT ALL * FROM tab1 AS cor0 WHERE 70 IS NULL
;

CREATE VIRTUAL VIEW V13 AS SELECT ALL 16 + + col2 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V14 AS SELECT + 84 + + + 29 AS col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V15 AS SELECT ( - - 98 ) FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V16 AS SELECT * FROM tab0 AS cor0 WHERE NULL NOT IN ( + col2, - col2 * - - 87 )
;

CREATE VIRTUAL VIEW V17 AS SELECT - 42 - col0 AS col0, col2 AS col1 FROM tab0
;

CREATE VIRTUAL VIEW V18 AS SELECT ALL col0 - - col1 * col0 FROM tab2
;

CREATE VIRTUAL VIEW V19 AS SELECT ALL - col2 * col1 AS col1, - 8 FROM tab1
;

CREATE VIRTUAL VIEW V20 AS SELECT ( col1 ) AS col0 FROM tab0 WHERE NOT ( - + col1 ) >= NULL
;

CREATE VIRTUAL VIEW V21 AS SELECT DISTINCT + 39 * col1 AS col1 FROM tab1 cor0
;

CREATE VIRTUAL VIEW V22 AS SELECT DISTINCT 99 * - + col2 AS col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V23 AS SELECT ALL * FROM tab1 AS cor0 WHERE NOT NULL <= 43
;

CREATE VIRTUAL VIEW V24 AS SELECT * FROM tab1 cor0 WHERE NOT NULL BETWEEN 66 AND + + col0
;

CREATE VIRTUAL VIEW V25 AS SELECT ALL + col2 * col0 * + col0 AS col0 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V26 AS SELECT DISTINCT + col2 * + 97 * - 54, - col2 AS col0 FROM tab1 cor0
;

CREATE VIRTUAL VIEW V27 AS SELECT 82 * + 4 AS col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V28 AS SELECT - col1, col1 AS col0 FROM tab2
;

CREATE VIRTUAL VIEW V29 AS SELECT ALL col1 * + 50 * col2 FROM tab1
;

CREATE VIRTUAL VIEW V30 AS SELECT ALL col0 * - + col2 AS col0 FROM tab1
;

CREATE VIRTUAL VIEW V31 AS SELECT col2, col0 FROM tab1
;

CREATE VIRTUAL VIEW V32 AS SELECT ALL + 23 + - 42 AS col0 FROM tab2
;

CREATE VIRTUAL VIEW V33 AS SELECT ALL col1 FROM tab1 AS cor0 WHERE + 55 IS NOT NULL
;

CREATE VIRTUAL VIEW V34 AS SELECT * FROM tab2 AS cor0 WHERE ( NOT ( + col0 ) NOT BETWEEN ( NULL ) AND NULL )
;

CREATE VIRTUAL VIEW V35 AS SELECT DISTINCT * FROM tab2 cor0 WHERE + col2 < - 92 * + 57 * - col0 + col2
;

CREATE VIRTUAL VIEW V36 AS SELECT ALL + + col1 * + - col1 + - 70 + - 99 AS col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V37 AS SELECT 62 - col2 + 1 AS col1 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V38 AS SELECT - + ( - + col0 ) * + - col1 - + - 64 AS col2 FROM tab2 cor0
;

CREATE VIRTUAL VIEW V39 AS SELECT + 93 + + ( - - col2 ) FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V40 AS SELECT DISTINCT * FROM tab0 AS cor0 WHERE ( NULL ) NOT IN ( col2 + col2, col0, + 62, - col0 + col2 + col1 )
;

CREATE VIRTUAL VIEW V41 AS SELECT ALL col0 - - - 29 FROM tab1
;

CREATE VIRTUAL VIEW V42 AS SELECT - - col2 * - + col1 + col1 * - col1 FROM tab2 WHERE NULL <> NULL
;

CREATE VIRTUAL VIEW V43 AS SELECT 50 + + + col0 FROM tab1
;

CREATE VIRTUAL VIEW V44 AS SELECT DISTINCT col2, - col0 FROM tab2
;

CREATE VIRTUAL VIEW V45 AS SELECT - 27 * + 32 AS col1 FROM tab0
;

CREATE VIRTUAL VIEW V46 AS SELECT DISTINCT 91 AS col0 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V47 AS SELECT * FROM tab2 AS cor0 WHERE NOT 29 IS NOT NULL
;

CREATE VIRTUAL VIEW V48 AS SELECT * FROM tab1 WHERE NOT 69 > NULL
;

CREATE VIRTUAL VIEW V49 AS SELECT DISTINCT - col0 * 26 AS col0, - col1 AS col0 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V50 AS SELECT + col1 + + - col2 FROM tab2
;

CREATE VIRTUAL VIEW V51 AS SELECT DISTINCT + 62 * + + col0 AS col2 FROM tab2
;

CREATE VIRTUAL VIEW V52 AS SELECT * FROM tab2 WHERE - + col1 * - 48 * - 97 + + col1 - - - 70 * - + col1 IS NULL
;

CREATE VIRTUAL VIEW V53 AS SELECT DISTINCT col0 + + col2 - + - col1 AS col0 FROM tab2 cor0
;

CREATE VIRTUAL VIEW V54 AS SELECT ALL - col1 + - + col1 AS col1 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V55 AS SELECT DISTINCT col0 * - - ( + - 72 ) * - + 38 + + 19 AS col0 FROM tab0
;

CREATE VIRTUAL VIEW V56 AS SELECT * FROM tab0 WHERE + - col2 = - col2
;

CREATE VIRTUAL VIEW V57 AS SELECT DISTINCT * FROM tab1 AS cor0 WHERE NOT ( - col2 + - 39 ) IS NULL
;

CREATE VIRTUAL VIEW V58 AS SELECT + col2 FROM tab0 AS cor0 WHERE col1 IS NULL
;

CREATE VIRTUAL VIEW V59 AS SELECT DISTINCT + + ( + + col1 ), + 49 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V60 AS SELECT + 26 AS col1 FROM tab0 cor0
;

CREATE VIRTUAL VIEW V61 AS SELECT DISTINCT * FROM tab2 WHERE ( + 52 = NULL )
;

CREATE VIRTUAL VIEW V62 AS SELECT * FROM tab0 WHERE NOT NULL NOT IN ( + - col2, + col2, - + 19, + + 6 )
;

CREATE VIRTUAL VIEW V63 AS SELECT ALL 87 AS col1 FROM tab2 cor0
;

CREATE VIRTUAL VIEW V64 AS SELECT ALL - + 11 * - col2 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V65 AS SELECT DISTINCT * FROM tab0 WHERE - 64 * - col1 + + 5 IN ( - - col1 )
;

CREATE VIRTUAL VIEW V66 AS SELECT DISTINCT + - col0 + - 43 * col1 + 93 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V67 AS SELECT + 73 + col0 AS col2 FROM tab0 WHERE - 76 * - 43 < - + 53
;

CREATE VIRTUAL VIEW V68 AS SELECT DISTINCT col0 * ( + 65 ) FROM tab0
;

CREATE VIRTUAL VIEW V69 AS SELECT DISTINCT 96 * + - 53 * + + col2 AS col2 FROM tab0
;

CREATE VIRTUAL VIEW V70 AS SELECT 15 + + - 11 FROM tab1
;

CREATE VIRTUAL VIEW V71 AS SELECT - col1 + - ( - 8 ) + - col1 AS col0 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V72 AS SELECT - + col0 + - ( col1 ) FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V73 AS SELECT ALL 39, 37 AS col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V74 AS SELECT ALL - 56 * + + col0 + - col1 - col1 FROM tab1 cor0 WHERE - col0 IS NOT NULL
;

CREATE VIRTUAL VIEW V75 AS SELECT DISTINCT col0 FROM tab0 AS cor0 WHERE NULL IS NOT NULL
;

CREATE VIRTUAL VIEW V76 AS SELECT * FROM tab2 WHERE NOT - col0 * col0 + - - col0 BETWEEN NULL AND + 17
;

CREATE VIRTUAL VIEW V77 AS SELECT * FROM tab0 WHERE NOT - + col1 IS NULL
;

CREATE VIRTUAL VIEW V78 AS SELECT ALL * FROM tab0 WHERE ( + + col2 * - col1 ) > - col1 * - - 54
;

CREATE VIRTUAL VIEW V79 AS SELECT * FROM tab2 WHERE NOT ( - 90 - - col1 ) IS NOT NULL
;

CREATE VIRTUAL VIEW V80 AS SELECT 14 AS col1, + col0 + + col1 + - col2 AS col2 FROM tab1
;

CREATE VIRTUAL VIEW V81 AS SELECT - 52 AS col2, 78 * - + 35 FROM tab1
;

CREATE VIRTUAL VIEW V82 AS SELECT * FROM tab2 WHERE NOT + col1 - + col1 IS NULL
;

CREATE VIRTUAL VIEW V83 AS SELECT DISTINCT - + col0 * + col1 AS col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V84 AS SELECT * FROM tab0 AS cor0 WHERE NOT + col1 NOT IN ( col0, 22, + col1 )
;

CREATE VIRTUAL VIEW V85 AS SELECT DISTINCT - 73 + - - col2 + - col2 + + col0 AS col0 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V86 AS SELECT DISTINCT * FROM tab1 AS cor0 WHERE + col0 = - 86
;

CREATE VIRTUAL VIEW V87 AS SELECT ALL col2 + + - 72 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V88 AS SELECT ALL + col2 + + ( 87 ) - + + 98 + - col1 * col1 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V89 AS SELECT DISTINCT + col0 * ( 65 ) AS col0 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V90 AS SELECT 2 FROM tab0 cor0 WHERE col2 IN ( + col1 )
;

CREATE VIRTUAL VIEW V91 AS SELECT + ( col1 ) * + col2 + - col0 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V92 AS SELECT ALL 5 + + 36 AS col2 FROM tab1
;

CREATE VIRTUAL VIEW V93 AS SELECT col2 * + + 45 FROM tab1
;

CREATE VIRTUAL VIEW V94 AS SELECT - col1 * - - 82 AS col1 FROM tab2
;

CREATE VIRTUAL VIEW V95 AS SELECT 36 * + 38 FROM tab0
;

CREATE VIRTUAL VIEW V96 AS SELECT col0 * - 61 AS col2 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V97 AS SELECT DISTINCT - col0 * 71 + col0 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V98 AS SELECT * FROM tab0 WHERE NOT ( col0 * 9 ) IS NOT NULL
;

CREATE VIRTUAL VIEW V99 AS SELECT DISTINCT * FROM tab2 WHERE NOT - col2 * 72 - + 8 IN ( + col1 + + ( - col1 ) )
;

CREATE VIRTUAL VIEW V100 AS SELECT ALL * FROM tab2 WHERE NOT - 30 >= col0
;

CREATE VIRTUAL VIEW V101 AS SELECT * FROM tab2 WHERE col2 + ( col2 ) * + col0 IS NOT NULL
;

CREATE VIRTUAL VIEW V102 AS SELECT DISTINCT * FROM tab0 WHERE NOT 45 BETWEEN - col0 AND NULL
;

CREATE VIRTUAL VIEW V103 AS SELECT + 18 * - col1 + - ( - col1 ) FROM tab0 WHERE NOT col0 <= col0
;

CREATE VIRTUAL VIEW V104 AS SELECT ALL col0 * + 94 + + col2 * 49 FROM tab1
;

CREATE VIRTUAL VIEW V105 AS SELECT DISTINCT + col1 * ( 75 * - ( ( 92 ) ) ) + - col1 AS col2 FROM tab1
;

CREATE VIRTUAL VIEW V106 AS SELECT DISTINCT - col1 - - col2 AS col0 FROM tab0 WHERE NULL IS NOT NULL
;

CREATE VIRTUAL VIEW V107 AS SELECT DISTINCT 20 - + col0 * 94 FROM tab0
;

CREATE VIRTUAL VIEW V108 AS SELECT + 9 + 94 AS col0 FROM tab0
;

CREATE VIRTUAL VIEW V109 AS SELECT ( - 62 ) AS col2 FROM tab0
;

CREATE VIRTUAL VIEW V110 AS SELECT DISTINCT - col0 + + 68 AS col1 FROM tab2
;

CREATE VIRTUAL VIEW V111 AS SELECT + 99 + 9 FROM tab2
;

CREATE VIRTUAL VIEW V112 AS SELECT ALL - ( 62 ) FROM tab0
;

CREATE VIRTUAL VIEW V113 AS SELECT - ( + ( 43 ) ) + - col0 FROM tab1 WHERE NOT ( NULL ) BETWEEN NULL AND + 39
;

CREATE VIRTUAL VIEW V114 AS SELECT * FROM tab2 WHERE ( + 72 * col2 ) <> NULL
;

CREATE VIRTUAL VIEW V115 AS SELECT - col2 / + col0 - 6 * col1 FROM tab0 AS cor0 WHERE NOT col1 IS NOT NULL
;

CREATE VIRTUAL VIEW V116 AS SELECT col2 * - 78 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V117 AS SELECT DISTINCT col2 FROM tab0 AS cor0 WHERE ( NULL ) NOT IN ( + 18 )
;

CREATE VIRTUAL VIEW V118 AS SELECT - col2 FROM tab1 AS cor0 WHERE + col1 > NULL
;

CREATE VIRTUAL VIEW V119 AS SELECT ALL * FROM tab1 cor0 WHERE col1 NOT IN ( col0 + 82 )
;

CREATE VIRTUAL VIEW V120 AS SELECT DISTINCT + 87 + col2 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V121 AS SELECT ALL - 36 AS col2 FROM tab1 AS cor0 WHERE ( - col0 ) >= + col0
;

CREATE VIRTUAL VIEW V122 AS SELECT ALL - col1 FROM tab0 AS cor0 WHERE ( 49 / - 86 ) IS NOT NULL
;

CREATE VIRTUAL VIEW V123 AS SELECT ALL + 63 FROM tab1 WHERE NOT 44 NOT BETWEEN - col0 AND - col2
;

CREATE VIRTUAL VIEW V124 AS SELECT col2 + 66 FROM tab2
;

CREATE VIRTUAL VIEW V125 AS SELECT DISTINCT + 68 AS col2 FROM tab1 WHERE NOT + col2 IN ( ( col0 ) )
;

CREATE VIRTUAL VIEW V126 AS SELECT - 50 + - 90 + col1 AS col1 FROM tab1
;

CREATE VIRTUAL VIEW V127 AS SELECT DISTINCT col0 * - 0 + - col1 * + col1 + 14 * + 13 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V128 AS SELECT ALL - col2 + + col1 + 89 * 53 AS col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V129 AS SELECT DISTINCT col2, + col1 * + + ( 23 ) * + col0 FROM tab2
;

CREATE VIRTUAL VIEW V130 AS SELECT ALL * FROM tab0 AS cor0 WHERE NOT col2 > - 4
;

CREATE VIRTUAL VIEW V131 AS SELECT - col2 * - - col2 + col2 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V132 AS SELECT DISTINCT - col2 AS col1 FROM tab2 AS cor0 WHERE NOT ( NULL ) NOT IN ( 75 )
;

CREATE VIRTUAL VIEW V133 AS SELECT + 85 * col1 AS col1 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V134 AS SELECT DISTINCT + col1 AS col2 FROM tab2 AS cor0 WHERE NOT NULL > - col0
;

CREATE VIRTUAL VIEW V135 AS SELECT col2 AS col1 FROM tab1 AS cor0 WHERE NOT - 4 + col2 IS NOT NULL
;

CREATE VIRTUAL VIEW V136 AS SELECT 40 * + 79 FROM tab1
;

CREATE VIRTUAL VIEW V137 AS SELECT DISTINCT ( col0 ) AS col1, 20 FROM tab1
;

CREATE VIRTUAL VIEW V138 AS SELECT DISTINCT * FROM tab1 WHERE NULL NOT BETWEEN - - 76 + 20 AND + 97
;

CREATE VIRTUAL VIEW V139 AS SELECT ( + - col1 ) AS col0 FROM tab1
;

CREATE VIRTUAL VIEW V140 AS SELECT ALL * FROM tab0 AS cor0 WHERE ( NULL NOT BETWEEN 78 * col2 AND 91 )
;

CREATE VIRTUAL VIEW V141 AS SELECT DISTINCT - - 72 * + col1 * - - col0 FROM tab0 cor0
;

CREATE VIRTUAL VIEW V142 AS SELECT ALL - col0 AS col0 FROM tab1 AS cor0 WHERE NOT ( + ( - col0 ) ) IS NOT NULL
;

CREATE VIRTUAL VIEW V143 AS SELECT * FROM tab1 AS cor0 WHERE ( col0 * col0 ) IS NOT NULL
;

CREATE VIRTUAL VIEW V144 AS SELECT DISTINCT * FROM tab1 AS cor0 WHERE ( col0 ) NOT IN ( + col0, 70 )
;

CREATE VIRTUAL VIEW V145 AS SELECT DISTINCT + col1 + + - 67 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V146 AS SELECT - 85, + col0 FROM tab1
;

CREATE VIRTUAL VIEW V147 AS SELECT ALL * FROM tab0 WHERE NULL NOT BETWEEN 65 AND - 74
;

CREATE VIRTUAL VIEW V148 AS SELECT DISTINCT * FROM tab1 WHERE NULL > ( - ( + - col1 ) / 25 + + 39 + + 1 / + col2 )
;

CREATE VIRTUAL VIEW V149 AS SELECT - col0 * 54 AS col2 FROM tab2
;

CREATE VIRTUAL VIEW V150 AS SELECT ALL * FROM tab2 WHERE + ( + col1 ) + - ( - col2 ) IS NULL
;

CREATE VIRTUAL VIEW V151 AS SELECT ALL * FROM tab1 WHERE - ( col1 ) / col2 / - ( + + ( + col0 ) ) - + 31 BETWEEN ( 1 ) AND col2
;

CREATE VIRTUAL VIEW V152 AS SELECT DISTINCT + col0 FROM tab1 WHERE col1 IS NULL
;

CREATE VIRTUAL VIEW V153 AS SELECT ALL - ( + - col1 ) AS col0, + col1 * - col2 + col0, + - col1 AS col1 FROM tab2 cor0
;

CREATE VIRTUAL VIEW V154 AS SELECT + col1 * - col0, + col0 + + 61 + col0 AS col2 FROM tab0 cor0 WHERE NOT ( NOT NULL IS NOT NULL )
;

CREATE VIRTUAL VIEW V155 AS SELECT + + 38 AS col1 FROM tab0 cor0
;

CREATE VIRTUAL VIEW V156 AS SELECT + col0 AS col2 FROM tab0 cor0 WHERE NOT ( NOT - 76 IS NULL )
;

CREATE VIRTUAL VIEW V157 AS SELECT DISTINCT - + 35 AS col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V158 AS SELECT + + col2 * - 27 + + 39 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V159 AS SELECT ALL - col1 * 23 AS col0 FROM tab2
;

CREATE VIRTUAL VIEW V160 AS SELECT ALL 63 * col2 AS col0 FROM tab1
;

CREATE VIRTUAL VIEW V161 AS SELECT * FROM tab0 WHERE NOT + col2 * - col2 >= NULL
;

CREATE VIRTUAL VIEW V162 AS SELECT ALL + 14 AS col2 FROM tab1 WHERE - ( + - 40 ) IS NOT NULL
;

CREATE VIRTUAL VIEW V163 AS SELECT ALL - - col1 AS col1 FROM tab1 AS cor0 WHERE ( col2 ) NOT IN ( + 90, + 68 )
;

CREATE VIRTUAL VIEW V164 AS SELECT DISTINCT + col1, col2 AS col0 FROM tab0 AS cor0 WHERE NOT 51 IS NOT NULL
;

CREATE VIRTUAL VIEW V165 AS SELECT col1 FROM tab2 WHERE ( ( NOT ( NULL BETWEEN NULL AND ( - col2 ) ) ) )
;

CREATE VIRTUAL VIEW V166 AS SELECT DISTINCT * FROM tab2 WHERE NULL NOT BETWEEN ( - + col2 * - + 36 ) AND - col1
;

CREATE VIRTUAL VIEW V167 AS SELECT * FROM tab1 AS cor0 WHERE + 44 * - col0 IS NOT NULL
;

CREATE VIRTUAL VIEW V168 AS SELECT ALL + 78 + + col0 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V169 AS SELECT ALL * FROM tab2 AS cor0 WHERE NULL = col1
;

CREATE VIRTUAL VIEW V170 AS SELECT * FROM tab2 AS cor0 WHERE ( - + col1 ) + - + col0 * - + col1 > + col0
;

CREATE VIRTUAL VIEW V171 AS SELECT DISTINCT + - 69 + + + ( - + col2 ) * + col2, col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V172 AS SELECT ALL - col2 * + col2 - + - 51 * + - col1 * - col1 + + col2 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V173 AS SELECT ALL - 69 + - col1 AS col1 FROM tab2 cor0
;

CREATE VIRTUAL VIEW V174 AS SELECT ALL col0 - col0 * - 40 * - + 86 + + ( - col1 ) FROM tab0
;

CREATE VIRTUAL VIEW V175 AS SELECT DISTINCT + col1 * 13 * + col1 AS col2, col0 - + + 28 FROM tab2
;

CREATE VIRTUAL VIEW V176 AS SELECT ALL - - col0 + col0 FROM tab1 WHERE NOT NULL IS NOT NULL
;

CREATE VIRTUAL VIEW V177 AS SELECT 82 * - col2 * - col0 AS col0 FROM tab0
;

CREATE VIRTUAL VIEW V178 AS SELECT DISTINCT col2 * - col1 AS col0 FROM tab0 AS cor0 WHERE NULL IS NULL
;

CREATE VIRTUAL VIEW V179 AS SELECT - 90 * - col2 AS col0 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V180 AS SELECT * FROM tab2 AS cor0 WHERE NOT ( - 43 <= NULL )
;

CREATE VIRTUAL VIEW V181 AS SELECT ALL * FROM tab0 AS cor0 WHERE NOT 75 NOT IN ( 66 )
;

CREATE VIRTUAL VIEW V182 AS SELECT + + ( 37 ) FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V183 AS SELECT * FROM tab0 AS cor0 WHERE NOT + col0 * - col0 IS NOT NULL
;

CREATE VIRTUAL VIEW V184 AS SELECT ALL * FROM tab2 AS cor0 WHERE NOT + col1 + - + 52 <> NULL
;

CREATE VIRTUAL VIEW V185 AS SELECT - 36 + + col1 AS col1 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V186 AS SELECT ALL + 96 AS col2 FROM tab0
;

CREATE VIRTUAL VIEW V187 AS SELECT - 56 AS col0 FROM tab0 WHERE NOT + - 66 IS NOT NULL
;

CREATE VIRTUAL VIEW V188 AS SELECT + ( - - col0 ) AS col1 FROM tab1
;

CREATE VIRTUAL VIEW V189 AS SELECT ALL * FROM tab1 AS cor0 WHERE + 44 IS NULL
;

CREATE VIRTUAL VIEW V190 AS SELECT ( + - ( + 95 ) ) AS col0 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V191 AS SELECT DISTINCT col2 * 38 + - ( - col0 ) FROM tab2 cor0
;

CREATE VIRTUAL VIEW V192 AS SELECT DISTINCT + col2 + 88 + - + col1 AS col2 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V193 AS SELECT DISTINCT 38 + ( - + col2 ) AS col0 FROM tab2
;

CREATE VIRTUAL VIEW V194 AS SELECT ALL * FROM tab2 WHERE ( 43 ) BETWEEN col2 + - - 2 AND NULL
;

CREATE VIRTUAL VIEW V195 AS SELECT col1 - - col2 AS col1, + 10 AS col1 FROM tab0
;

CREATE VIRTUAL VIEW V196 AS SELECT ALL + ( col2 ) - + 57 FROM tab1
;

CREATE VIRTUAL VIEW V197 AS SELECT - col1 AS col1 FROM tab1 WHERE 5 IS NULL
;

CREATE VIRTUAL VIEW V198 AS SELECT DISTINCT * FROM tab0 AS cor0 WHERE NOT 31 * - - 88 BETWEEN - - 57 AND NULL
;

CREATE VIRTUAL VIEW V199 AS SELECT * FROM tab2 AS cor0 WHERE NOT ( NULL ) > + col0
;

CREATE VIRTUAL VIEW V200 AS SELECT - + ( + 5 ) FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V201 AS SELECT col0 * + - 94 AS col2 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V202 AS SELECT ALL * FROM tab2 AS cor0 WHERE NOT ( 75 ) IS NULL
;

CREATE VIRTUAL VIEW V203 AS SELECT * FROM tab1 AS cor0 WHERE NOT ( ( col1 ) ) BETWEEN col1 * - col2 AND 49 / - - col0
;

CREATE VIRTUAL VIEW V204 AS SELECT ALL + col0 AS col0, - col2 FROM tab2 AS cor0 WHERE NOT NULL NOT IN ( 84 )
;

CREATE VIRTUAL VIEW V205 AS SELECT ALL * FROM tab1 cor0 WHERE NOT NULL <> - col0
;

CREATE VIRTUAL VIEW V206 AS SELECT ALL col0 AS col2, + col0 * 56 AS col0 FROM tab1
;

CREATE VIRTUAL VIEW V207 AS SELECT 42 + - + 51 * + col2 AS col1 FROM tab0
;

CREATE VIRTUAL VIEW V208 AS SELECT - col2 + - - col0 FROM tab1 cor0
;

CREATE VIRTUAL VIEW V209 AS SELECT DISTINCT * FROM tab1 WHERE NOT NULL <= 99
;

CREATE VIRTUAL VIEW V210 AS SELECT + 82 * - col1, col2 AS col1 FROM tab2
;

CREATE VIRTUAL VIEW V211 AS SELECT ALL * FROM tab1 AS cor0 WHERE NOT NULL IS NOT NULL AND - col0 * - + 72 IS NULL
;

CREATE VIRTUAL VIEW V212 AS SELECT ALL - col1 + col2 * col0 AS col0 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V213 AS SELECT ALL - 20 + - - col2 AS col0, col1 AS col2 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V214 AS SELECT * FROM tab0 cor0 WHERE col0 NOT IN ( - col2 )
;

CREATE VIRTUAL VIEW V215 AS SELECT DISTINCT - ( - col1 ) * - + 66 FROM tab0
;

CREATE VIRTUAL VIEW V216 AS SELECT + - 18 * + 21 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V217 AS SELECT DISTINCT col1, 13 * col1 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V218 AS SELECT DISTINCT - + col0 FROM tab1 WHERE - col1 + + col0 < col2
;

CREATE VIRTUAL VIEW V219 AS SELECT ALL * FROM tab2 WHERE - col1 BETWEEN ( - + 17 ) AND - 68
;

CREATE VIRTUAL VIEW V220 AS SELECT ALL - - 72 AS col2 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V221 AS SELECT * FROM tab0 cor0 WHERE NOT - 97 IS NOT NULL
;

CREATE VIRTUAL VIEW V222 AS SELECT * FROM tab1 AS cor0 WHERE ( + 56 ) IS NULL
;

CREATE VIRTUAL VIEW V223 AS SELECT ALL - 22 AS col2, col2 * 47 + + col0 + - + col2 * + - col1 FROM tab1
;

CREATE VIRTUAL VIEW V224 AS SELECT ALL 68 + col1 + + + 63 FROM tab2
;

CREATE VIRTUAL VIEW V225 AS SELECT DISTINCT - col2 + + - col2 AS col0 FROM tab2 AS cor0 WHERE NOT col1 <= NULL
;

CREATE VIRTUAL VIEW V226 AS SELECT ALL + col0 + - - 55 AS col0 FROM tab2 AS cor0
;


CREATE VIRTUAL VIEW V227 AS SELECT col0 + + + col1 - - col2 FROM tab1 AS cor0 WHERE NULL IS NULL
;

CREATE VIRTUAL VIEW V228 AS SELECT ALL + col1 + - col0 + + - col1 + + col2 * + 84 - - 88 AS col1 FROM tab2 AS cor0 WHERE - col0 IS NOT NULL
;

CREATE VIRTUAL VIEW V229 AS SELECT * FROM tab1 cor0 WHERE NOT - ( + col1 ) IS NULL
;

CREATE VIRTUAL VIEW V230 AS SELECT DISTINCT + col1, - col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V231 AS SELECT ALL * FROM tab2 WHERE NULL BETWEEN ( + col0 + - 78 ) AND + col1
;

CREATE VIRTUAL VIEW V232 AS SELECT + ( + col2 ) FROM tab1 WHERE NOT NULL >= + col0
;

CREATE VIRTUAL VIEW V233 AS SELECT DISTINCT - 84 AS col1 FROM tab1
;

CREATE VIRTUAL VIEW V234 AS SELECT DISTINCT + col2 * + col0 * - col0 AS col2 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V235 AS SELECT ALL + col1 FROM tab0 AS cor0 WHERE 66 <> NULL
;

CREATE VIRTUAL VIEW V236 AS SELECT + col0, - 47 + - col2 FROM tab2 AS cor0 WHERE NOT col0 * - - col0 - - 57 BETWEEN NULL AND + - 18 - + 12
;

CREATE VIRTUAL VIEW V237 AS SELECT - + col2 * + ( - col1 ) AS col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V238 AS SELECT 53 FROM tab0 AS cor0 WHERE NOT ( NULL ) IS NULL
;

CREATE VIRTUAL VIEW V239 AS SELECT + - col0 + col1 AS col2, - col0 FROM tab2 WHERE NOT NULL <= NULL
;

CREATE VIRTUAL VIEW V240 AS SELECT * FROM tab0 AS cor0 WHERE 29 * - 84 IS NULL
;

CREATE VIRTUAL VIEW V241 AS SELECT + col1, + 94 * + 73 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V242 AS SELECT ALL ( - col2 ) + - + col1 AS col2 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V243 AS SELECT - 74, + col0 FROM tab2 cor0
;

CREATE VIRTUAL VIEW V244 AS SELECT DISTINCT - col1 + - 10 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V245 AS SELECT ALL * FROM tab2 WHERE NOT - 54 IS NOT NULL
;

CREATE VIRTUAL VIEW V246 AS SELECT DISTINCT - ( - 13 ) * - col2 + + ( - col1 ) AS col0, 2 + + 25 AS col2 FROM tab0
;

CREATE VIRTUAL VIEW V247 AS SELECT ALL + col1 + - - 76 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V248 AS SELECT ALL col2 * + ( 51 ) - + - 95 AS col0 FROM tab0
;

CREATE VIRTUAL VIEW V249 AS SELECT + + 53 * + - col0 AS col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V250 AS SELECT DISTINCT - 75 AS col0 FROM tab1 cor0 WHERE NOT + 68 * - col0 <> - 37
;

CREATE VIRTUAL VIEW V251 AS SELECT ALL ( - 64 ) FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V252 AS SELECT ALL + col0, col0 AS col1 FROM tab1
;

CREATE VIRTUAL VIEW V253 AS SELECT DISTINCT - 71 AS col1, 62 AS col1 FROM tab0
;

CREATE VIRTUAL VIEW V254 AS SELECT ALL - col0 AS col2, - 83 AS col0 FROM tab2
;

CREATE VIRTUAL VIEW V255 AS SELECT ALL * FROM tab2 AS cor0 WHERE ( NULL ) <= NULL
;

CREATE VIRTUAL VIEW V256 AS SELECT ALL - 27 AS col1 FROM tab2 WHERE NOT - col1 IS NULL
;

CREATE VIRTUAL VIEW V257 AS SELECT ALL 9 * + - col2 AS col1 FROM tab2
;

CREATE VIRTUAL VIEW V258 AS SELECT ALL * FROM tab0 WHERE NOT ( + col1 IN ( 70, 18 ) )
;

CREATE VIRTUAL VIEW V259 AS SELECT DISTINCT - - 78 + ( - + col1 ) AS col0 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V260 AS SELECT ALL + col1 * 30 FROM tab0
;

CREATE VIRTUAL VIEW V261 AS SELECT - col0 * 25 FROM tab1
;

CREATE VIRTUAL VIEW V262 AS SELECT ALL - 76 + col0 AS col1 FROM tab1
;

CREATE VIRTUAL VIEW V263 AS SELECT ( + col2 ) - 95 AS col0 FROM tab0
;

CREATE VIRTUAL VIEW V264 AS SELECT ALL + ( ( + - col1 ) ) FROM tab0
;


CREATE VIRTUAL VIEW V265 AS SELECT DISTINCT col1 FROM tab0 AS cor0 WHERE NOT + col2 + - 10 / col1 IS NULL
;

CREATE VIRTUAL VIEW V266 AS SELECT col2 * 57 + + - col1 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V267 AS SELECT DISTINCT * FROM tab1 cor0 WHERE NOT + 80 - 86 IS NULL
;

CREATE VIRTUAL VIEW V268 AS SELECT DISTINCT + 54 * + ( col2 ) AS col1 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V269 AS SELECT + + col2 * 30 FROM tab1 WHERE NOT + ( col0 ) IS NOT NULL
;

CREATE VIRTUAL VIEW V270 AS SELECT * FROM tab0 WHERE NOT ( NULL <> NULL )
;

CREATE VIRTUAL VIEW V271 AS SELECT + 45 AS col1 FROM tab2
;

CREATE VIRTUAL VIEW V272 AS SELECT DISTINCT + - 47 + col1 - - col2, col0 * - col0 FROM tab1 cor0 WHERE NOT col0 IS NOT NULL
;

CREATE VIRTUAL VIEW V273 AS SELECT DISTINCT col1 + 92 * ( - col1 ) FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V274 AS SELECT * FROM tab2 WHERE NULL NOT BETWEEN + ( + col0 ) AND NULL
;

CREATE VIRTUAL VIEW V275 AS SELECT ALL - col0 AS col0 FROM tab2 WHERE ( col2 ) <> 92 * col2
;

CREATE VIRTUAL VIEW V276 AS SELECT + 5 * + ( + + 59 ) FROM tab1 cor0
;

CREATE VIRTUAL VIEW V277 AS SELECT - + 19 - col0 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V278 AS SELECT DISTINCT col2 FROM tab1 cor0 WHERE - col1 IS NULL
;

CREATE VIRTUAL VIEW V279 AS SELECT - col0 + - 17 * 76 * col0 AS col0 FROM tab0 cor0
;

CREATE VIRTUAL VIEW V280 AS SELECT DISTINCT 96 + - col2 + - 99 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V281 AS SELECT ALL 10 + 76 * 69 FROM tab0
;

CREATE VIRTUAL VIEW V282 AS SELECT - ( + col1 ) + col0 * col2 AS col2 FROM tab2
;

CREATE VIRTUAL VIEW V283 AS SELECT ALL + 88 FROM tab1 WHERE col1 * - col1 > NULL
;

CREATE VIRTUAL VIEW V284 AS SELECT ALL * FROM tab0 WHERE NULL IN ( - - 42, col2 / - col0, ( col0 ), + col2 )
;

CREATE VIRTUAL VIEW V285 AS SELECT - 52 * col2 + + col1, ( + + col0 ) FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V286 AS SELECT DISTINCT + col0 FROM tab1 cor0 WHERE NOT col1 + 26 NOT BETWEEN + col1 + - col2 + - 97 AND NULL
;

CREATE VIRTUAL VIEW V287 AS SELECT - 10 * + col1 AS col0 FROM tab2
;


CREATE VIRTUAL VIEW V288 AS SELECT - - col0 AS col1, ( + col2 ) FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V289 AS SELECT ALL - + col1 AS col1, + col1 AS col0 FROM tab2 cor0
;

CREATE VIRTUAL VIEW V290 AS SELECT ALL - col1 AS col0 FROM tab2 AS cor0 WHERE NOT NULL BETWEEN - col2 + + col2 AND + + col2
;

CREATE VIRTUAL VIEW V291 AS SELECT DISTINCT - - col0 * - 27 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V292 AS SELECT DISTINCT - 15 AS col0 FROM tab1
;

CREATE VIRTUAL VIEW V293 AS SELECT + 59 AS col1 FROM tab0
;

CREATE VIRTUAL VIEW V294 AS SELECT * FROM tab2 WHERE NOT col1 = col1 - col1
;

CREATE VIRTUAL VIEW V295 AS SELECT DISTINCT + - col1 FROM tab1 WHERE - + ( - + col2 ) = + col2
;

CREATE VIRTUAL VIEW V296 AS SELECT ALL col2 + + 80 AS col1 FROM tab2 cor0
;

CREATE VIRTUAL VIEW V297 AS SELECT ALL col1 + + 1 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V298 AS SELECT ALL * FROM tab2 AS cor0 WHERE NOT - col1 <= + col1
;

CREATE VIRTUAL VIEW V299 AS SELECT ALL - col0 + - + ( - - ( + col0 ) ) FROM tab2 cor0
;

CREATE VIRTUAL VIEW V300 AS SELECT + col2, col0 * - col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V301 AS SELECT ALL - 88 + + - col0 * - col0 FROM tab0
;

CREATE VIRTUAL VIEW V302 AS SELECT - 93 * 62 - - ( col1 ) FROM tab2
;

CREATE VIRTUAL VIEW V303 AS SELECT ( - + col1 ) - ( col1 ) + + 85 * - - 55, - 55 * + ( + + col1 ) AS col2 FROM tab2
;

CREATE VIRTUAL VIEW V304 AS SELECT * FROM tab1 WHERE + col0 = - 31
;

CREATE VIRTUAL VIEW V305 AS SELECT DISTINCT * FROM tab1 WHERE NOT col2 <> + - 30 * + + col2
;

CREATE VIRTUAL VIEW V306 AS SELECT * FROM tab0 AS cor0 WHERE NOT ( NULL ) NOT BETWEEN ( + - 67 ) AND - ( - + col2 ) * - 25
;

CREATE VIRTUAL VIEW V307 AS SELECT * FROM tab1 AS cor0 WHERE NOT + col1 = 65 * + col0 * col1
;

CREATE VIRTUAL VIEW V308 AS SELECT ALL col1 * - col0 + col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V309 AS SELECT + col0, - col1 AS col2 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V310 AS SELECT DISTINCT * FROM tab2 AS cor0 WHERE NOT ( ( NOT 87 <= - - ( + col1 ) ) )
;

CREATE VIRTUAL VIEW V311 AS SELECT * FROM tab0 AS cor0 WHERE NOT col0 + - col1 * col1 BETWEEN NULL AND NULL
;

CREATE VIRTUAL VIEW V312 AS SELECT + 56 * ( - 40 ) AS col2 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V313 AS SELECT - 63 * - ( + - 77 ) FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V314 AS SELECT ALL col0 * + + 22 AS col0 FROM tab2
;

CREATE VIRTUAL VIEW V315 AS SELECT DISTINCT - 48 + - - col1 AS col0 FROM tab2
;

CREATE VIRTUAL VIEW V316 AS SELECT + 16 + + + col1 * col1 + col0 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V317 AS SELECT DISTINCT * FROM tab2 AS cor0 WHERE NOT NULL < NULL
;

CREATE VIRTUAL VIEW V318 AS SELECT ALL + col1 * - col0 + - 1 * + + col0 AS col0 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V319 AS SELECT col2 + + col2 * - + col2 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V320 AS SELECT ALL col1 AS col0, col2 FROM tab2
;

CREATE VIRTUAL VIEW V321 AS SELECT DISTINCT * FROM tab1 AS cor0 WHERE - ( - + col0 ) IS NULL
;

CREATE VIRTUAL VIEW V322 AS SELECT DISTINCT - + 11 FROM tab2 cor0
;

CREATE VIRTUAL VIEW V323 AS SELECT ALL + 31, - 57 AS col2 FROM tab0 WHERE - col2 IS NOT NULL
;

CREATE VIRTUAL VIEW V324 AS SELECT ALL + - col1 FROM tab0 WHERE + ( + 65 ) * - col1 BETWEEN + 31 + col1 - 61 + - 69 * col1 AND NULL
;

CREATE VIRTUAL VIEW V325 AS SELECT col1 AS col2, 10 + - col1 AS col1 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V326 AS SELECT ALL + - 57 * - 90 * + col1 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V327 AS SELECT DISTINCT - + col2 * - col2 * 26 + 3 - + + col2 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V328 AS SELECT + col2 * - col1, col1 + + + col2 AS col2 FROM tab0
;

CREATE VIRTUAL VIEW V329 AS SELECT - col1 AS col2 FROM tab0 WHERE NULL >= + col1
;

CREATE VIRTUAL VIEW V330 AS SELECT - 35 * + col0 AS col1 FROM tab1
;

CREATE VIRTUAL VIEW V331 AS SELECT col2 AS col1 FROM tab1 AS cor0 WHERE + col0 IS NULL
;

CREATE VIRTUAL VIEW V332 AS SELECT DISTINCT * FROM tab1 AS cor0 WHERE 38 * + col1 IS NULL
;

CREATE VIRTUAL VIEW V333 AS SELECT - col0 + + col0 + - + col2 FROM tab0
;

CREATE VIRTUAL VIEW V334 AS SELECT * FROM tab2 AS cor0 WHERE ( + col2 IS NOT NULL )
;

CREATE VIRTUAL VIEW V335 AS SELECT - col0 * + col2 + - col2 * - col1 AS col1 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V336 AS SELECT * FROM tab0 AS cor0 WHERE NULL < col1 * + col2 - + col0
;

CREATE VIRTUAL VIEW V337 AS SELECT ALL ( - 90 ) FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V338 AS SELECT ( + - col0 ) AS col0, col0 AS col0 FROM tab1
;

CREATE VIRTUAL VIEW V339 AS SELECT DISTINCT 31 + + col0 * + ( + col0 ) FROM tab2 WHERE + - col2 IS NOT NULL
;

CREATE VIRTUAL VIEW V340 AS SELECT * FROM tab0 WHERE NOT + col2 BETWEEN + + col1 AND NULL
;

CREATE VIRTUAL VIEW V341 AS SELECT col1 AS col1 FROM tab1 WHERE NOT NULL IS NULL
;

CREATE VIRTUAL VIEW V342 AS SELECT col1 * - 80 AS col1 FROM tab2
;

CREATE VIRTUAL VIEW V343 AS SELECT DISTINCT + col1, 17 FROM tab1 AS cor0 WHERE ( NULL ) IS NULL
;

CREATE VIRTUAL VIEW V344 AS SELECT ALL col1 + - - ( - col1 ) AS col0 FROM tab1
;

CREATE VIRTUAL VIEW V345 AS SELECT ALL + + 86 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V346 AS SELECT - - col2 + + - ( - ( - - col0 ) ) FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V347 AS SELECT 11 - + col0 + + col0 * - col1 * - col1 AS col0 FROM tab0
;

CREATE VIRTUAL VIEW V348 AS SELECT DISTINCT - 46 * 16 AS col0, 78 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V349 AS SELECT ALL col2, - col1 AS col1 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V350 AS SELECT col0 - + col2 FROM tab1 WHERE NOT - 11 + + col1 > NULL
;

CREATE VIRTUAL VIEW V351 AS SELECT + 50 AS col1 FROM tab1 WHERE NOT ( 7 ) <= 30
;

CREATE VIRTUAL VIEW V352 AS SELECT ALL + col1 FROM tab2 WHERE NOT NULL IS NULL
;

CREATE VIRTUAL VIEW V353 AS SELECT DISTINCT col0 AS col2 FROM tab0 WHERE NOT 15 NOT BETWEEN 24 AND col0 * - 33 + 28
;

CREATE VIRTUAL VIEW V354 AS SELECT + 47 + - col1 AS col1 FROM tab2
;

CREATE VIRTUAL VIEW V355 AS SELECT DISTINCT + col2 * col1 + + col0 FROM tab1
;

CREATE VIRTUAL VIEW V356 AS SELECT * FROM tab1 WHERE - col2 >= + 16
;

CREATE VIRTUAL VIEW V357 AS SELECT ALL - col2 + col0 * col2 AS col1 FROM tab2
;

CREATE VIRTUAL VIEW V358 AS SELECT * FROM tab0 WHERE NOT ( col0 * - 8 ) = NULL
;

CREATE VIRTUAL VIEW V359 AS SELECT col0 + ( 68 ) FROM tab2
;

CREATE VIRTUAL VIEW V360 AS SELECT 86 + col2 AS col0 FROM tab2
;

CREATE VIRTUAL VIEW V361 AS SELECT 24 + - 61 FROM tab1
;

CREATE VIRTUAL VIEW V362 AS SELECT - col1 - - col0 * col0 AS col2 FROM tab0 WHERE - col2 * 13 IS NULL
;

CREATE VIRTUAL VIEW V363 AS SELECT ALL - 38 * + col1 FROM tab2
;

CREATE VIRTUAL VIEW V364 AS SELECT col0 * - 28 AS col1 FROM tab2
;

CREATE VIRTUAL VIEW V365 AS SELECT * FROM tab1 WHERE NOT + col1 + - col2 / 43 IN ( + col2 )
;

CREATE VIRTUAL VIEW V366 AS SELECT * FROM tab1 WHERE NOT ( + 8 + col2 ) IS NULL
;

CREATE VIRTUAL VIEW V367 AS SELECT * FROM tab1 WHERE NOT - col0 + - 85 * + ( - col0 ) NOT BETWEEN + 21 AND - 73 + + col0
;

CREATE VIRTUAL VIEW V368 AS SELECT + ( + col0 ) + ( - col0 ) FROM tab1
;

CREATE VIRTUAL VIEW V369 AS SELECT DISTINCT - col2 * - 36 + + 47 AS col0 FROM tab2 cor0
;

CREATE VIRTUAL VIEW V370 AS SELECT DISTINCT * FROM tab1 AS cor0 WHERE NULL BETWEEN ( NULL ) AND NULL
;

CREATE VIRTUAL VIEW V371 AS SELECT * FROM tab1 cor0 WHERE ( + col0 ) NOT BETWEEN - col2 * col1 AND ( NULL )
;

CREATE VIRTUAL VIEW V372 AS SELECT DISTINCT col1 AS col0 FROM tab2 AS cor0 WHERE - ( ( 35 ) ) IS NOT NULL
;

CREATE VIRTUAL VIEW V373 AS SELECT DISTINCT ( + 28 ) + + 70 AS col1 FROM tab0 AS cor0 WHERE NOT NULL NOT BETWEEN + col0 AND - col0 * col1
;

CREATE VIRTUAL VIEW V374 AS SELECT ALL * FROM tab1 cor0 WHERE ( col0 ) IS NOT NULL
;

CREATE VIRTUAL VIEW V375 AS SELECT ALL col1 - 89 FROM tab1
;

CREATE VIRTUAL VIEW V376 AS SELECT ALL + col2 AS col0 FROM tab0 WHERE col0 + col2 >= + col2 / ( col0 )
;

CREATE VIRTUAL VIEW V377 AS SELECT ALL 16 + - 85 * - col2 FROM tab0
;

CREATE VIRTUAL VIEW V378 AS SELECT col0 AS col0 FROM tab2 AS cor0 WHERE NOT NULL >= + col1
;

CREATE VIRTUAL VIEW V379 AS SELECT ALL col2 * ( - ( col0 ) ) AS col2 FROM tab0 AS cor0 WHERE NOT NULL IS NOT NULL
;

CREATE VIRTUAL VIEW V380 AS SELECT * FROM tab1 AS cor0 WHERE NOT col0 NOT BETWEEN - 95 * - ( 40 ) AND - col0 * col0
;

CREATE VIRTUAL VIEW V381 AS SELECT - ( - col2 ) * + col1 AS col1 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V382 AS SELECT + 61 * col2 AS col2 FROM tab1 AS cor0 WHERE NOT 76 NOT IN ( 54 )
;

CREATE VIRTUAL VIEW V383 AS SELECT * FROM tab2 AS cor0 WHERE NOT col0 - - col1 NOT BETWEEN - col2 * col0 AND + col1
;

CREATE VIRTUAL VIEW V384 AS SELECT DISTINCT - col1 FROM tab0 WHERE NULL < - col1
;

CREATE VIRTUAL VIEW V385 AS SELECT ALL ( + col1 ) * - col1 AS col0 FROM tab1
;

CREATE VIRTUAL VIEW V386 AS SELECT DISTINCT col2 AS col1 FROM tab1 AS cor0 WHERE col1 * + col2 < + col2
;

CREATE VIRTUAL VIEW V387 AS SELECT + col0 + 52 AS col2 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V388 AS SELECT 81 + col2 FROM tab2 cor0
;

CREATE VIRTUAL VIEW V389 AS SELECT ALL * FROM tab2 WHERE NOT + ( - 69 ) * col2 IS NULL
;


CREATE VIRTUAL VIEW V390 AS SELECT * FROM tab0 AS cor0 WHERE NULL NOT BETWEEN ( NULL ) AND + col2
;

CREATE VIRTUAL VIEW V391 AS SELECT * FROM tab2 AS cor0 WHERE 21 NOT IN ( - - col0 )
;

CREATE VIRTUAL VIEW V392 AS SELECT DISTINCT + 22 * 90 * + col1 + col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V393 AS SELECT DISTINCT ( + col2 ) + 21 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V394 AS SELECT ALL + col2 + + - 74 AS col0 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V395 AS SELECT ALL * FROM tab0 AS cor0 WHERE ( + col1 ) IS NOT NULL
;

CREATE VIRTUAL VIEW V396 AS SELECT ( col2 ) + + col2 * - col0 AS col2 FROM tab2 cor0 WHERE ( - col2 ) BETWEEN ( NULL ) AND ( NULL )
;

CREATE VIRTUAL VIEW V397 AS SELECT DISTINCT col2 - col2 AS col1 FROM tab2 AS cor0 WHERE ( NULL ) IS NOT NULL
;

CREATE VIRTUAL VIEW V398 AS SELECT ( col2 ) + + - col0 FROM tab1
;

CREATE VIRTUAL VIEW V399 AS SELECT * FROM tab1 AS cor0 WHERE NULL >= + 97 * - 83
;

CREATE VIRTUAL VIEW V400 AS SELECT * FROM tab2 cor0 WHERE + col1 <= + 78 * - - col2 + ( col0 + - col0 ) * + 94
;

CREATE VIRTUAL VIEW V401 AS SELECT col1 * + col2 - col2 AS col2 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V402 AS SELECT ALL * FROM tab1 cor0 WHERE col1 * + - col2 IS NOT NULL
;

CREATE VIRTUAL VIEW V403 AS SELECT DISTINCT + 95 * - 55 AS col0 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V404 AS SELECT * FROM tab2 AS cor0 WHERE + 75 >= NULL
;

CREATE VIRTUAL VIEW V405 AS SELECT DISTINCT * FROM tab0 AS cor0 WHERE 73 + + 19 IS NOT NULL
;

CREATE VIRTUAL VIEW V406 AS SELECT DISTINCT + col0 * - col0 * + ( + col1 ) * + + col0 FROM tab2
;

CREATE VIRTUAL VIEW V407 AS SELECT ALL 45 * col0 * + + col0 AS col1 FROM tab1
;

CREATE VIRTUAL VIEW V408 AS SELECT ALL 36 FROM tab0 AS cor0 WHERE NOT + col2 * - 20 IN ( + 55 + - col0 )
;

CREATE VIRTUAL VIEW V409 AS SELECT DISTINCT 56 + col2 AS col2 FROM tab0 WHERE NOT col1 + + col2 * + - ( + - 9 ) IS NULL
;

CREATE VIRTUAL VIEW V410 AS SELECT + col1, 5 AS col0 FROM tab0
;

CREATE VIRTUAL VIEW V411 AS SELECT * FROM tab2 WHERE NOT ( - - ( + col2 ) * + col0 * - col1 + col0 ) < NULL
;

CREATE VIRTUAL VIEW V412 AS SELECT ALL - - col0 FROM tab0 WHERE ( NULL ) < - 76
;

CREATE VIRTUAL VIEW V413 AS SELECT ALL - col2 AS col2, col2 * + 30 FROM tab1
;

CREATE VIRTUAL VIEW V414 AS SELECT DISTINCT - 30 + + - col2 AS col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V415 AS SELECT col0 + 12 + + col0 FROM tab2
;

CREATE VIRTUAL VIEW V416 AS SELECT DISTINCT * FROM tab2 WHERE NOT - 21 IS NULL
;

CREATE VIRTUAL VIEW V417 AS SELECT ALL * FROM tab0 AS cor0 WHERE NOT ( NULL >= NULL )
;

CREATE VIRTUAL VIEW V418 AS SELECT ALL - col0 FROM tab2 AS cor0 WHERE col2 / col1 = NULL
;

CREATE VIRTUAL VIEW V419 AS SELECT - + 37 + + 60 AS col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V420 AS SELECT ALL * FROM tab1 AS cor0 WHERE + 17 * + - 5 IS NULL
;

CREATE VIRTUAL VIEW V421 AS SELECT ALL + ( + col0 ) FROM tab0 cor0 WHERE NULL IN ( 14, - ( - ( + + col0 ) ) )
;

CREATE VIRTUAL VIEW V422 AS SELECT ALL * FROM tab0 WHERE - col0 > NULL
;

CREATE VIRTUAL VIEW V423 AS SELECT DISTINCT ( - - 58 ) FROM tab2
;

CREATE VIRTUAL VIEW V424 AS SELECT DISTINCT + col2 AS col2 FROM tab0 AS cor0 WHERE NOT NULL IS NULL AND + col0 * + col0 IS NOT NULL
;

CREATE VIRTUAL VIEW V425 AS SELECT * FROM tab2 WHERE NOT NULL BETWEEN - col2 AND - col2
;

CREATE VIRTUAL VIEW V426 AS SELECT col2 + col2 FROM tab0 WHERE NOT + col0 >= + + col1
;

CREATE VIRTUAL VIEW V427 AS SELECT * FROM tab0 AS cor0 WHERE NOT col1 IN ( + col0 )
;

CREATE VIRTUAL VIEW V428 AS SELECT * FROM tab0 AS cor0 WHERE NOT NULL NOT IN ( - col2 + - col1, col1 )
;

CREATE VIRTUAL VIEW V429 AS SELECT ALL * FROM tab2 AS cor0 WHERE - col0 IS NULL
;

CREATE VIRTUAL VIEW V430 AS SELECT + 49 * 19 AS col1 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V431 AS SELECT DISTINCT + col1 FROM tab0 cor0 WHERE 47 NOT BETWEEN - 91 AND NULL
;

CREATE VIRTUAL VIEW V432 AS SELECT * FROM tab1 WHERE NOT col2 >= col2
;

CREATE VIRTUAL VIEW V433 AS SELECT ALL col1 FROM tab2 WHERE NULL IS NOT NULL
;

CREATE VIRTUAL VIEW V434 AS SELECT DISTINCT - ( 71 ) * + col1 AS col0 FROM tab2
;

CREATE VIRTUAL VIEW V435 AS SELECT DISTINCT - col0 * - 62 AS col2 FROM tab2
;

CREATE VIRTUAL VIEW V436 AS SELECT - col0 AS col2, 89 + + 99 FROM tab0
;

CREATE VIRTUAL VIEW V437 AS SELECT + col1 + - 36 AS col1 FROM tab1
;

CREATE VIRTUAL VIEW V438 AS SELECT - col0 + + + col1 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V439 AS SELECT * FROM tab1 AS cor0 WHERE ( + 38 ) IS NULL
;

CREATE VIRTUAL VIEW V440 AS SELECT col2 * 57 - + 91 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V441 AS SELECT ALL * FROM tab0 AS cor0 WHERE NOT NULL IS NOT NULL AND ( NOT ( NOT NULL NOT IN ( + 40 ) ) )
;

CREATE VIRTUAL VIEW V442 AS SELECT ALL - col2 * + col2 - + 12 AS col0 FROM tab0
;

CREATE VIRTUAL VIEW V443 AS SELECT * FROM tab1 WHERE ( NULL ) >= + 37
;

CREATE VIRTUAL VIEW V444 AS SELECT + col1 + - 44 - 74 AS col0 FROM tab0
;

CREATE VIRTUAL VIEW V445 AS SELECT + ( + + col0 ) AS col1 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V446 AS SELECT ALL + 56 AS col2 FROM tab1 cor0
;

CREATE VIRTUAL VIEW V447 AS SELECT ALL * FROM tab0 AS cor0 WHERE NOT + col1 <= - - 48 * + col1 * col0
;

CREATE VIRTUAL VIEW V448 AS SELECT col2 * col1 * - + col2 FROM tab2
;

CREATE VIRTUAL VIEW V449 AS SELECT * FROM tab2 WHERE NOT 59 NOT IN ( col2, 9 * - + col2 / - col2 )
;

CREATE VIRTUAL VIEW V450 AS SELECT col2 * + col2 * - col1 AS col1 FROM tab0
;

CREATE VIRTUAL VIEW V451 AS SELECT ALL + col0 * + col1 * + 7 FROM tab1
;

CREATE VIRTUAL VIEW V452 AS SELECT ALL col2 * + col1 * + 9 * ( + 84 ) AS col0 FROM tab1
;

CREATE VIRTUAL VIEW V453 AS SELECT col0 * + col0 AS col2, + col1 FROM tab0
;

CREATE VIRTUAL VIEW V454 AS SELECT DISTINCT + 6 + col1 AS col2 FROM tab2
;

CREATE VIRTUAL VIEW V455 AS SELECT * FROM tab2 WHERE + 38 IS NULL
;

CREATE VIRTUAL VIEW V456 AS SELECT + 50 * + - 55 - + col2 AS col0 FROM tab2 WHERE col1 + col1 BETWEEN + - col0 AND NULL
;

CREATE VIRTUAL VIEW V457 AS SELECT * FROM tab0 WHERE - col0 - - + 61 * - - col2 * - 94 IS NULL
;

CREATE VIRTUAL VIEW V458 AS SELECT DISTINCT - col0 AS col2 FROM tab2 AS cor0 WHERE - col1 + - + col2 * col0 BETWEEN NULL AND - - 15 + + col1
;

CREATE VIRTUAL VIEW V459 AS SELECT ALL + 73 * + - 35 + ( - - 46 ), + col1 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V460 AS SELECT col1 + + ( - 95 ) FROM tab0
;

CREATE VIRTUAL VIEW V461 AS SELECT ALL + - 0 AS col0 FROM tab0 cor0
;

CREATE VIRTUAL VIEW V462 AS SELECT ALL - col0 + - + 69 AS col2 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V463 AS SELECT ALL + col0 * + + 5 - - - col2 - + col2 FROM tab2 cor0
;

CREATE VIRTUAL VIEW V464 AS SELECT CAST(SUM ( + col1 ) AS INTEGER) FROM tab2 AS cor0 WHERE NULL > NULL
;

CREATE VIRTUAL VIEW V465 AS SELECT ALL col1 FROM tab1 WHERE NULL NOT BETWEEN NULL AND ( col1 ) AND NULL IS NULL
;

CREATE VIRTUAL VIEW V466 AS SELECT - col1 - + 53 - - col1 * + 88 FROM tab2
;

CREATE VIRTUAL VIEW V467 AS SELECT ALL + col2 + 49 FROM tab1
;

CREATE VIRTUAL VIEW V468 AS SELECT * FROM tab1 AS cor0 WHERE NOT + col1 + + col0 + - col0 <> NULL
;

CREATE VIRTUAL VIEW V469 AS SELECT - 65 * - 15 AS col0 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V470 AS SELECT DISTINCT + + col0 * 18 AS col2 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V471 AS SELECT + - 65 * - + col1 + col2 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V472 AS SELECT DISTINCT + col1 AS col0, 82 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V473 AS SELECT DISTINCT + + CAST(SUM ( ALL + col2 ) AS INTEGER) FROM tab1 AS cor0 WHERE + col2 IS NULL
;

CREATE VIRTUAL VIEW V474 AS SELECT ALL col0 + 71 * + + 75 + - col1 - - + col0 + + + col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V475 AS SELECT ALL - 18 AS col0 FROM tab0
;

CREATE VIRTUAL VIEW V476 AS SELECT + ( + 12 ) - - col2 FROM tab1 AS cor0 WHERE + col2 + - - 31 > ( col2 ) + - ( col0 )
;

CREATE VIRTUAL VIEW V477 AS SELECT - - 60 + ( + col0 ) FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V478 AS SELECT 63 + + - 38 AS col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V479 AS SELECT DISTINCT 15 + - col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V480 AS SELECT ALL - col2 * + + 61 + - col2 + - col0 AS col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V481 AS SELECT ALL * FROM tab0 cor0 WHERE NOT + ( col2 ) < - 63 + col2
;

CREATE VIRTUAL VIEW V482 AS SELECT + - col1 + + - 85 - - col1 * + - col1, col1 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V483 AS SELECT * FROM tab1 WHERE NOT col0 + + col2 < + 11
;

CREATE VIRTUAL VIEW V484 AS SELECT col1, + col2 AS col2 FROM tab0
;

CREATE VIRTUAL VIEW V485 AS SELECT DISTINCT - col0 AS col1, - col0 AS col0 FROM tab2 cor0 WHERE col1 / - - ( - col0 ) > NULL
;

CREATE VIRTUAL VIEW V486 AS SELECT * FROM tab0 AS cor0 WHERE NOT ( col1 ) IS NULL
;

CREATE VIRTUAL VIEW V487 AS SELECT DISTINCT + 28 * - - ( + + col0 ) FROM tab2 cor0
;

CREATE VIRTUAL VIEW V488 AS SELECT DISTINCT + ( + 72 ) FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V489 AS SELECT ALL col0 * 36 * 84 * - col1 FROM tab1
;

CREATE VIRTUAL VIEW V490 AS SELECT ALL + col0 + + 32 AS col0 FROM tab1 WHERE NOT NULL IS NULL
;

CREATE VIRTUAL VIEW V491 AS SELECT ALL col1 * col0 * - col0 AS col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V492 AS SELECT * FROM tab0 cor0 WHERE NOT - 73 * + col2 IS NOT NULL
;

CREATE VIRTUAL VIEW V493 AS SELECT ALL 46 * col0 AS col2 FROM tab0
;

CREATE VIRTUAL VIEW V494 AS SELECT DISTINCT - - col1 + col1 AS col0 FROM tab0 WHERE NOT NULL IS NULL
;

CREATE VIRTUAL VIEW V495 AS SELECT ALL col0 * - + col2 * + col0 AS col0 FROM tab0
;

CREATE VIRTUAL VIEW V496 AS SELECT + col2 * - 0, - col0 AS col2 FROM tab1
;

CREATE VIRTUAL VIEW V497 AS SELECT DISTINCT - + col1 + 29 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V498 AS SELECT - + col1 AS col0 FROM tab2 AS cor0 WHERE ( NOT NULL IS NULL )
;

CREATE VIRTUAL VIEW V499 AS SELECT ALL + 15 + + col0 * + col0 * col0 AS col1 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V500 AS SELECT col1 + + 64 + + col0 AS col2 FROM tab1
;

CREATE VIRTUAL VIEW V501 AS SELECT - col0 FROM tab2 cor0 WHERE + 53 * - - col2 * - ( + col0 ) IN ( - 51 )
;

CREATE VIRTUAL VIEW V502 AS SELECT - 58 + 6, col1 * + + 59 + col1 FROM tab1 AS cor0 WHERE NOT NULL NOT BETWEEN NULL AND + col1
;

CREATE VIRTUAL VIEW V503 AS SELECT DISTINCT - ( - - col1 ) AS col2 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V504 AS SELECT - - col0, col0 * - col1 AS col2 FROM tab1 AS cor0 WHERE NOT + col1 IS NOT NULL
;

CREATE VIRTUAL VIEW V505 AS SELECT ALL + 63 * + + 97 AS col2 FROM tab0 cor0 WHERE NOT ( NULL ) <> - 33
;

CREATE VIRTUAL VIEW V506 AS SELECT ALL col0 * + ( col2 ) AS col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V507 AS SELECT ALL + col2 * - 85 FROM tab0
;

CREATE VIRTUAL VIEW V508 AS SELECT * FROM tab0 AS cor0 WHERE NOT + col0 NOT BETWEEN - col2 / col2 + - 32 AND NULL
;

CREATE VIRTUAL VIEW V509 AS SELECT DISTINCT + - 89 AS col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V510 AS SELECT ALL - - col0 * + col0 + - + col2 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V511 AS SELECT ALL 26 FROM tab1 AS cor0 WHERE NULL IS NULL
;

CREATE VIRTUAL VIEW V512 AS SELECT DISTINCT col1 + - 79 + - + 26 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V513 AS SELECT - - col1 AS col0 FROM tab2 AS cor0 WHERE - col0 - col1 IS NULL
;

CREATE VIRTUAL VIEW V514 AS SELECT ALL * FROM tab1 WHERE NOT + col1 * + col0 * - ( - - 5 ) IS NOT NULL
;

CREATE VIRTUAL VIEW V515 AS SELECT DISTINCT - col0 * - col0 * - col1 + + col0 FROM tab2
;

CREATE VIRTUAL VIEW V516 AS SELECT DISTINCT 95 * + 28 * - col1 AS col2 FROM tab1
;

CREATE VIRTUAL VIEW V517 AS SELECT DISTINCT + col2 * + col1 * + + 41 FROM tab1
;

CREATE VIRTUAL VIEW V518 AS SELECT DISTINCT + col1 * - ( - 69 ) AS col0 FROM tab1
;

CREATE VIRTUAL VIEW V519 AS SELECT DISTINCT - col0, col2 FROM tab1
;

CREATE VIRTUAL VIEW V520 AS SELECT ALL col2 AS col0, col2 AS col0 FROM tab0
;

CREATE VIRTUAL VIEW V521 AS SELECT ALL * FROM tab2 AS cor0 WHERE NOT + col2 <> NULL
;

CREATE VIRTUAL VIEW V522 AS SELECT DISTINCT * FROM tab1 AS cor0 WHERE ( NULL ) IN ( col2, col0 )
;

CREATE VIRTUAL VIEW V523 AS SELECT + + col1 * + col2 + + 58 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V524 AS SELECT DISTINCT + col0 * - - col2 + + + 76 FROM tab2 AS cor0 WHERE NOT NULL > NULL
;

CREATE VIRTUAL VIEW V525 AS SELECT DISTINCT * FROM tab1 AS cor0 WHERE NOT 16 BETWEEN NULL AND col2
;

CREATE VIRTUAL VIEW V526 AS SELECT * FROM tab2 WHERE NOT - col2 <> + 61 * - - col0 * - col0 * - col1
;

CREATE VIRTUAL VIEW V527 AS SELECT ALL * FROM tab0 AS cor0 WHERE col1 + - - 69 IS NOT NULL
;

CREATE VIRTUAL VIEW V528 AS SELECT ALL * FROM tab2 AS cor0 WHERE NOT 33 * + - ( 66 ) >= - col0
;

CREATE VIRTUAL VIEW V529 AS SELECT * FROM tab0 AS cor0 WHERE NOT - col2 * 41 <= NULL
;

CREATE VIRTUAL VIEW V530 AS SELECT ALL - 2 + - col0 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V531 AS SELECT DISTINCT - + col1 + + ( col0 ) AS col1 FROM tab1 cor0
;

CREATE VIRTUAL VIEW V532 AS SELECT - 24 * 82 AS col2, + col1 AS col0 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V533 AS SELECT ALL 0 * - col1 * - col0 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V534 AS SELECT * FROM tab1 cor0 WHERE ( NULL ) >= - col2 + - 96
;

CREATE VIRTUAL VIEW V535 AS SELECT ALL + col1 * 32 AS col2 FROM tab0
;

CREATE VIRTUAL VIEW V536 AS SELECT + 84 - + - col1 * col1 * + 33 AS col0 FROM tab1
;

CREATE VIRTUAL VIEW V537 AS SELECT ALL 50 * col1 AS col1 FROM tab1 WHERE NOT ( NOT - col2 IS NULL )
;

CREATE VIRTUAL VIEW V538 AS SELECT ALL * FROM tab2 AS cor0 WHERE NULL NOT BETWEEN ( NULL ) AND + - 89
;

CREATE VIRTUAL VIEW V539 AS SELECT - 96 FROM tab2 AS cor0 WHERE ( NOT NULL IS NULL ) OR NOT ( NULL ) NOT BETWEEN 74 * - - ( + col0 ) / + col1 * + col0 AND NULL
;

CREATE VIRTUAL VIEW V540 AS SELECT DISTINCT * FROM tab2 WHERE 96 > NULL
;

CREATE VIRTUAL VIEW V541 AS SELECT DISTINCT 21 AS col2, col2 AS col1 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V542 AS SELECT + col0 AS col2 FROM tab1 cor0 WHERE NOT NULL IS NOT NULL
;

CREATE VIRTUAL VIEW V543 AS SELECT * FROM tab2 AS cor0 WHERE NOT ( NOT ( + col2 IS NOT NULL ) )
;

CREATE VIRTUAL VIEW V544 AS SELECT * FROM tab2 AS cor0 WHERE NOT ( NULL >= + col0 )
;

CREATE VIRTUAL VIEW V545 AS SELECT + ( + col2 ), - ( - + col2 ) AS col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V546 AS SELECT ALL + + 1 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V547 AS SELECT * FROM tab2 WHERE NOT - 23 IS NULL
;

CREATE VIRTUAL VIEW V548 AS SELECT DISTINCT col1 + + 81 FROM tab2
;

CREATE VIRTUAL VIEW V549 AS SELECT DISTINCT + 65 + + 76 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V550 AS SELECT ALL * FROM tab1 AS cor0 WHERE NOT NULL NOT BETWEEN ( NULL ) AND 1
;

CREATE VIRTUAL VIEW V551 AS SELECT ALL * FROM tab1 WHERE ( - col1 ) IS NOT NULL
;

CREATE VIRTUAL VIEW V552 AS SELECT ALL - 84 * + + col2 AS col1 FROM tab2
;

CREATE VIRTUAL VIEW V553 AS SELECT DISTINCT + col1 + col0 * + + col0 FROM tab0 cor0
;

CREATE VIRTUAL VIEW V554 AS SELECT DISTINCT ( - CAST(SUM ( DISTINCT + 59 ) AS INTEGER) ) AS col0 FROM tab0 AS cor0 WHERE 56 BETWEEN + - col1 * col2 * col1 + - col0 + - col1 * - - 13 + - col2 + - col1 + + 97 AND NULL
;

CREATE VIRTUAL VIEW V555 AS SELECT DISTINCT col0 + - ( + col0 ) AS col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V556 AS SELECT - 92 + - col2 FROM tab1 cor0
;

CREATE VIRTUAL VIEW V557 AS SELECT - col1 FROM tab1 WHERE + col2 = + + 81 + col0
;

CREATE VIRTUAL VIEW V558 AS SELECT DISTINCT * FROM tab1 WHERE - col2 >= - col1
;

CREATE VIRTUAL VIEW V559 AS SELECT DISTINCT col0 - - - col1, ( 72 ) * col1 * + 92 AS col2 FROM tab1
;

CREATE VIRTUAL VIEW V560 AS SELECT - 2 * col0 AS col0, + 90 FROM tab1
;

CREATE VIRTUAL VIEW V561 AS SELECT DISTINCT * FROM tab2 WHERE NOT NULL NOT BETWEEN - col2 * + col0 AND - ( col1 )
;

CREATE VIRTUAL VIEW V562 AS SELECT ALL * FROM tab2 WHERE NOT col2 * col0 + + col2 + + 85 IS NULL
;


CREATE VIRTUAL VIEW V563 AS SELECT ALL - col0 * + 10 + + 43 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V564 AS SELECT * FROM tab1 AS cor0 WHERE NOT ( NULL ) NOT BETWEEN 55 - + 53 - + - col0 / + col1 AND NULL
;

CREATE VIRTUAL VIEW V565 AS SELECT ALL col2 + - col0 + + + col2 AS col1 FROM tab2 AS cor0 WHERE NOT col2 * + col0 * + - 64 NOT BETWEEN + - col1 * - col0 + - col0 AND ( NULL )
;

CREATE VIRTUAL VIEW V566 AS SELECT - col0 AS col2, - col1 AS col1 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V567 AS SELECT col2 AS col1 FROM tab2 AS cor0 WHERE NOT NULL IS NULL
;

CREATE VIRTUAL VIEW V568 AS SELECT col2 AS col2, col1 + + 19 FROM tab1
;

CREATE VIRTUAL VIEW V569 AS SELECT ALL + 72 * + 97 FROM tab1
;

CREATE VIRTUAL VIEW V570 AS SELECT * FROM tab1 AS cor0 WHERE NOT NULL < + col0
;

CREATE VIRTUAL VIEW V571 AS SELECT DISTINCT - + col0 FROM tab1 AS cor0 WHERE NOT NULL NOT IN ( - col2, col1 )
;

CREATE VIRTUAL VIEW V572 AS SELECT DISTINCT col0 + - + col0 * - col1 AS col0 FROM tab0 cor0
;

CREATE VIRTUAL VIEW V573 AS SELECT DISTINCT 42 * + - col0 + col1 - - col1 FROM tab1 cor0
;

CREATE VIRTUAL VIEW V574 AS SELECT 83 * + col0 AS col0 FROM tab0 AS cor0 WHERE NULL IS NOT NULL
;

CREATE VIRTUAL VIEW V575 AS SELECT DISTINCT + + 33 * + col0 - + - col0 + 91 * - 99 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V576 AS SELECT - 26 - + col0 FROM tab0
;

CREATE VIRTUAL VIEW V577 AS SELECT col1 * - - 70 FROM tab2 WHERE + - col0 IS NOT NULL
;

CREATE VIRTUAL VIEW V578 AS SELECT + col2 - col0 * - + col1 FROM tab0
;

CREATE VIRTUAL VIEW V579 AS SELECT DISTINCT 82 AS col1 FROM tab2
;

CREATE VIRTUAL VIEW V580 AS SELECT DISTINCT * FROM tab1 AS cor0 WHERE NOT + 82 * col2 IS NULL
;

CREATE VIRTUAL VIEW V581 AS SELECT DISTINCT col0 AS col0 FROM tab0 WHERE NULL IN ( - col2 )
;

CREATE VIRTUAL VIEW V582 AS SELECT DISTINCT + col1 * - col2 AS col2 FROM tab2 WHERE + col2 IS NULL
;

CREATE VIRTUAL VIEW V583 AS SELECT ALL + col2 * - + 67 + col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V584 AS SELECT * FROM tab2 AS cor0 WHERE NOT - col2 <= - 56
;

CREATE VIRTUAL VIEW V585 AS SELECT DISTINCT col1, 95 FROM tab2
;

CREATE VIRTUAL VIEW V586 AS SELECT DISTINCT + + ( col0 ) + - + col2 * + 83 + + - col0 FROM tab0 WHERE NULL IS NULL
;

CREATE VIRTUAL VIEW V587 AS SELECT DISTINCT col0 FROM tab0 WHERE NOT NULL = - col0
;

CREATE VIRTUAL VIEW V588 AS SELECT * FROM tab0 WHERE - col2 > - col0
;

CREATE VIRTUAL VIEW V589 AS SELECT 13 + col1 + - + col0 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V590 AS SELECT DISTINCT + ( - 82 ) * + col0 + - - col0 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V591 AS SELECT * FROM tab1 AS cor0 WHERE 28 * - + col1 IS NULL
;

CREATE VIRTUAL VIEW V592 AS SELECT * FROM tab1 WHERE col2 * col0 >= + 41
;

CREATE VIRTUAL VIEW V593 AS SELECT DISTINCT - 65 AS col2 FROM tab0 WHERE + 22 + - col0 IS NOT NULL
;

CREATE VIRTUAL VIEW V594 AS SELECT ALL 47 + + col2 AS col2 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V595 AS SELECT col0 + - col0 + - col1 FROM tab0 cor0
;

CREATE VIRTUAL VIEW V596 AS SELECT 28 * - col1 AS col1 FROM tab1 AS cor0 WHERE NULL IS NOT NULL
;

CREATE VIRTUAL VIEW V597 AS SELECT DISTINCT col1 + - - 94 + col2 - ( 92 ) * - col2 * col0 AS col1 FROM tab1
;

CREATE VIRTUAL VIEW V598 AS SELECT DISTINCT ( + - col1 ) FROM tab0
;

CREATE VIRTUAL VIEW V599 AS SELECT ALL + col1 + + 0 FROM tab2 WHERE NULL IS NOT NULL
;

CREATE VIRTUAL VIEW V600 AS SELECT ALL * FROM tab2 WHERE + + col1 + col1 IS NOT NULL
;

CREATE VIRTUAL VIEW V601 AS SELECT - 38 * - 3 * + 30 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V602 AS SELECT ALL * FROM tab0 AS cor0 WHERE 97 < + 21
;

CREATE VIRTUAL VIEW V603 AS SELECT + + ( col1 ) + + 39 * col1 AS col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V604 AS SELECT ALL * FROM tab0 cor0 WHERE col2 <> - col0
;

CREATE VIRTUAL VIEW V605 AS SELECT DISTINCT + 45 * col0 AS col0 FROM tab2
;

CREATE VIRTUAL VIEW V606 AS SELECT * FROM tab1 WHERE NULL >= - + col0 + + - col1
;

CREATE VIRTUAL VIEW V607 AS SELECT ALL col0 * - 5, col0 FROM tab2
;

CREATE VIRTUAL VIEW V608 AS SELECT DISTINCT 33 * - 15 AS col2 FROM tab1
;

CREATE VIRTUAL VIEW V609 AS SELECT ALL - col1 + col1 AS col2, col0 * + - 35 FROM tab0
;

CREATE VIRTUAL VIEW V610 AS SELECT - + 24 FROM tab2 AS cor0 WHERE + col1 * + col1 + col0 + - col1 IS NULL
;

CREATE VIRTUAL VIEW V611 AS SELECT ALL + + 77 + col0 * col2 AS col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V612 AS SELECT + col2 + + - 82 AS col0 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V613 AS SELECT ALL - 24, col0 * + col2 + + 11 AS col0 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V614 AS SELECT - 23 AS col1, 13 AS col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V615 AS SELECT ALL + col0 * - col0 FROM tab1 WHERE + + 33 * + 25 IS NULL
;

CREATE VIRTUAL VIEW V616 AS SELECT col2, 60 AS col0 FROM tab0
;

CREATE VIRTUAL VIEW V617 AS SELECT DISTINCT * FROM tab2 WHERE NOT + col0 + - 84 IS NULL
;

CREATE VIRTUAL VIEW V618 AS SELECT - - col2 * - - 65 * - + 81 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V619 AS SELECT ALL col0 + 3 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V620 AS SELECT DISTINCT - col0 + col1 + 85 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V621 AS SELECT ALL col2 FROM tab0 WHERE NOT ( NOT NULL IS NULL )
;

CREATE VIRTUAL VIEW V622 AS SELECT DISTINCT + col1 + + 79 FROM tab1
;

CREATE VIRTUAL VIEW V623 AS SELECT col1 + + 97 AS col2 FROM tab0
;

CREATE VIRTUAL VIEW V624 AS SELECT 26 + - 5 AS col1 FROM tab1
;

CREATE VIRTUAL VIEW V625 AS SELECT ALL * FROM tab2 WHERE NOT ( NULL ) <= - ( - col2 )
;

CREATE VIRTUAL VIEW V626 AS SELECT col2 AS col1 FROM tab2 WHERE ( + col0 ) <= 45 * col1 - col1
;

CREATE VIRTUAL VIEW V627 AS SELECT * FROM tab0 WHERE NOT 30 = ( NULL )
;

CREATE VIRTUAL VIEW V628 AS SELECT + ( col2 ) FROM tab1 WHERE NULL IS NULL
;

CREATE VIRTUAL VIEW V629 AS SELECT DISTINCT - col2 AS col2 FROM tab0 WHERE + 37 * col0 NOT IN ( + col1 )
;

CREATE VIRTUAL VIEW V630 AS SELECT + ( + col1 ) + col0 FROM tab1
;

CREATE VIRTUAL VIEW V631 AS SELECT + 18 + col1 AS col1 FROM tab2
;

CREATE VIRTUAL VIEW V632 AS SELECT ALL * FROM tab1 WHERE - col0 * - col1 <> ( - col1 )
;

CREATE VIRTUAL VIEW V633 AS SELECT * FROM tab2 WHERE NOT ( - 63 * - col2 ) IS NOT NULL
;

CREATE VIRTUAL VIEW V634 AS SELECT * FROM tab0 WHERE ( 63 + - col0 ) IS NULL
;

CREATE VIRTUAL VIEW V635 AS SELECT 4 + + 45 FROM tab2
;

CREATE VIRTUAL VIEW V636 AS SELECT col2 + ( col2 ) * 18 AS col0 FROM tab2
;

CREATE VIRTUAL VIEW V637 AS SELECT col0 * 98 + col1 AS col1 FROM tab2
;

CREATE VIRTUAL VIEW V638 AS SELECT - 83 - + 82 FROM tab1
;

CREATE VIRTUAL VIEW V639 AS SELECT + col0 * + col2 AS col0 FROM tab0 WHERE NOT NULL > NULL
;

CREATE VIRTUAL VIEW V640 AS SELECT DISTINCT - col2 + 59 FROM tab1
;

CREATE VIRTUAL VIEW V641 AS SELECT DISTINCT * FROM tab1 WHERE - col1 * ( 25 ) + + col2 IN ( col0 )
;

CREATE VIRTUAL VIEW V642 AS SELECT * FROM tab1 AS cor0 WHERE NOT ( 68 + + col0 * col0 ) NOT BETWEEN col0 * col1 + - col2 * - col1 AND col2
;

CREATE VIRTUAL VIEW V643 AS SELECT DISTINCT 98 + - col0 FROM tab1 WHERE NOT ( - col0 ) NOT IN ( + col0 )
;


CREATE VIRTUAL VIEW V644 AS SELECT ALL 93 FROM tab0 cor0 WHERE ( - 57 ) IS NULL
;

CREATE VIRTUAL VIEW V645 AS SELECT - 7 + + col1 AS col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V646 AS SELECT DISTINCT + 54 + + col1 AS col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V647 AS SELECT * FROM tab0 AS cor0 WHERE col0 <= col1
;

CREATE VIRTUAL VIEW V648 AS SELECT DISTINCT + 85 + 66 AS col0 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V649 AS SELECT * FROM tab2 AS cor0 WHERE - col1 NOT BETWEEN ( NULL ) AND NULL
;

CREATE VIRTUAL VIEW V650 AS SELECT ALL 82 FROM tab2 WHERE ( + 53 ) IS NOT NULL OR NOT 79 + - col2 NOT BETWEEN + col2 * - col0 AND ( - 47 * col1 )
;

CREATE VIRTUAL VIEW V651 AS SELECT - col1 * + + col1 FROM tab0
;

CREATE VIRTUAL VIEW V652 AS SELECT DISTINCT * FROM tab2 WHERE NOT col0 + col0 IS NOT NULL
;

CREATE VIRTUAL VIEW V653 AS SELECT 1 - - - col1 + - col0 AS col0 FROM tab2
;

CREATE VIRTUAL VIEW V654 AS SELECT ALL + col0 + + col1 - + col2 AS col0 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V655 AS SELECT - col0 AS col1, - 19 FROM tab1
;

CREATE VIRTUAL VIEW V656 AS SELECT DISTINCT col2 FROM tab2 AS cor0 WHERE NOT col0 IS NULL
;

CREATE VIRTUAL VIEW V657 AS SELECT DISTINCT - ( - col1 ) + 4 AS col0 FROM tab1 AS cor0 WHERE NOT + col2 + 50 IS NULL
;

CREATE VIRTUAL VIEW V658 AS SELECT DISTINCT + col2 * - - ( - ( col0 ) ) FROM tab0 cor0
;

CREATE VIRTUAL VIEW V659 AS SELECT ALL - col0 * - - 11 FROM tab1 cor0
;

CREATE VIRTUAL VIEW V660 AS SELECT + col0 * + 95 + - col1 AS col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V661 AS SELECT DISTINCT * FROM tab0 AS cor0 WHERE NOT ( + 59 ) IS NULL
;

CREATE VIRTUAL VIEW V662 AS SELECT * FROM tab2 WHERE NOT ( + + ( - col2 ) ) IS NOT NULL
;

CREATE VIRTUAL VIEW V663 AS SELECT DISTINCT * FROM tab0 WHERE ( + - col2 / + col1 ) <= - col0
;

CREATE VIRTUAL VIEW V664 AS SELECT DISTINCT * FROM tab2 WHERE col1 < - - ( + col1 )
;

CREATE VIRTUAL VIEW V665 AS SELECT ALL + - col1 FROM tab0 AS cor0 WHERE 15 IS NOT NULL
;

CREATE VIRTUAL VIEW V666 AS SELECT col0 + - + 85 AS col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V667 AS SELECT ALL col0 AS col2 FROM tab0 AS cor0 WHERE NOT ( + col0 ) IS NOT NULL
;

CREATE VIRTUAL VIEW V668 AS SELECT ALL - col1 * col1 - col0 + + ( - 66 ) FROM tab1 cor0
;

CREATE VIRTUAL VIEW V669 AS SELECT + ( - 80 ) FROM tab0 AS cor0 WHERE ( 51 ) IS NULL
;

CREATE VIRTUAL VIEW V670 AS SELECT ALL + + 53 + 67 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V671 AS SELECT ALL + col0 + + col1 + 15 * 93 * + col0 AS col1 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V672 AS SELECT + col2 + + 44 + + - 13 * - - 17 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V673 AS SELECT ALL 63 + + - col2 AS col1 FROM tab1
;

CREATE VIRTUAL VIEW V674 AS SELECT ALL * FROM tab2 AS cor0 WHERE col2 * 46 IS NOT NULL
;

CREATE VIRTUAL VIEW V675 AS SELECT + ( + + 62 ) AS col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V676 AS SELECT * FROM tab1 cor0 WHERE - col1 NOT BETWEEN - col0 AND + + 5
;

CREATE VIRTUAL VIEW V677 AS SELECT ALL - col1 * + ( col2 ) FROM tab2
;

CREATE VIRTUAL VIEW V678 AS SELECT DISTINCT + 85 AS col0 FROM tab1
;

CREATE VIRTUAL VIEW V679 AS SELECT + ( - col2 ) * + + col2 AS col2 FROM tab0 cor0
;

CREATE VIRTUAL VIEW V680 AS SELECT - + col1 * 72 FROM tab2 cor0
;

CREATE VIRTUAL VIEW V681 AS SELECT ALL * FROM tab0 cor0 WHERE 31 * - + col2 <= ( + + col0 )
;

CREATE VIRTUAL VIEW V682 AS SELECT - ( + - 88 ) FROM tab0 AS cor0 WHERE NOT ( ( NULL <= - 51 ) )
;

CREATE VIRTUAL VIEW V683 AS SELECT ALL * FROM tab0 AS cor0 WHERE NOT col1 > - col2
;

CREATE VIRTUAL VIEW V684 AS SELECT + 75 * - + 32 AS col2 FROM tab1
;

CREATE VIRTUAL VIEW V685 AS SELECT + col1 * - 14 * - col0 FROM tab1
;

CREATE VIRTUAL VIEW V686 AS SELECT * FROM tab0 WHERE NOT + - ( 24 ) IS NULL
;

CREATE VIRTUAL VIEW V687 AS SELECT - col1 AS col1, 81 AS col2 FROM tab0
;

CREATE VIRTUAL VIEW V688 AS SELECT * FROM tab0 WHERE NOT NULL < + 1
;

CREATE VIRTUAL VIEW V689 AS SELECT + col1 * 33 FROM tab0
;

CREATE VIRTUAL VIEW V690 AS SELECT 5 AS col1, col2 AS col2 FROM tab0
;

CREATE VIRTUAL VIEW V691 AS SELECT DISTINCT + 60 AS col0 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V692 AS SELECT DISTINCT 99 + - col0 * - 21 AS col0 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V693 AS SELECT - col0 + - 99 FROM tab0
;

CREATE VIRTUAL VIEW V694 AS SELECT DISTINCT + + col2 + 58 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V695 AS SELECT DISTINCT col1 - + - 63 FROM tab2
;

CREATE VIRTUAL VIEW V696 AS SELECT 91 * - - col0 - + col1 AS col2 FROM tab1
;

CREATE VIRTUAL VIEW V697 AS SELECT + 15 AS col1 FROM tab2 AS cor0 WHERE NOT NULL IS NOT NULL
;

CREATE VIRTUAL VIEW V698 AS SELECT DISTINCT + ( 75 ) * - + 20 * + + col1 AS col1, + col0 AS col1 FROM tab1
;

CREATE VIRTUAL VIEW V699 AS SELECT DISTINCT - - 26 * col2 + + 25 AS col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V700 AS SELECT * FROM tab0 cor0 WHERE NOT - 66 / + 25 IS NULL
;

CREATE VIRTUAL VIEW V701 AS SELECT - - 67 * 99 * - col1 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V702 AS SELECT * FROM tab1 AS cor0 WHERE NOT ( NULL ) > col2 * + ( + ( + + col0 ) ) * - 60
;

CREATE VIRTUAL VIEW V703 AS SELECT + col1 * 57 AS col0 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V704 AS SELECT ALL * FROM tab0 WHERE NOT ( - 9 * + col1 ) IS NOT NULL
;

CREATE VIRTUAL VIEW V705 AS SELECT DISTINCT col1 * + ( - - col2 ) AS col0 FROM tab2
;

CREATE VIRTUAL VIEW V706 AS SELECT 77 + - + col1 + col0 * - - 94 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V707 AS SELECT * FROM tab0 AS cor0 WHERE ( NOT + col1 + + col1 - col0 IS NULL )
;

CREATE VIRTUAL VIEW V708 AS SELECT ALL + col2 + 19 + - col0 * + 78 * + 61 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V709 AS SELECT ALL + 59 + + + col2 AS col1 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V710 AS SELECT ALL + - col1 + + 98 + + ( - col1 ) FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V711 AS SELECT ALL col2 - + - 82 FROM tab0
;

CREATE VIRTUAL VIEW V712 AS SELECT DISTINCT - col2 - + ( + col2 ) FROM tab1
;

CREATE VIRTUAL VIEW V713 AS SELECT + col1 * - + col0 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V714 AS SELECT + ( - - 41 ) * + - 74 + + 51 + 48, col0 AS col0 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V715 AS SELECT - col0 + + col1 FROM tab0 WHERE NOT NULL IS NOT NULL
;

CREATE VIRTUAL VIEW V716 AS SELECT 26 * col2 AS col2 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V717 AS SELECT DISTINCT 5 FROM tab2 AS cor0 WHERE NOT NULL IS NOT NULL
;

CREATE VIRTUAL VIEW V718 AS SELECT DISTINCT * FROM tab0 AS cor0 WHERE NOT ( - 65 ) > + col2 + col2 * + 87 + + ( col1 )
;

CREATE VIRTUAL VIEW V719 AS SELECT ALL 14 * - col2 * col0 * + - col2 FROM tab0 AS cor0 WHERE NOT ( NULL ) <= + - col1 * - + 11 / - col0
;

CREATE VIRTUAL VIEW V720 AS SELECT - col0 * - - col0 + 66 AS col0 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V721 AS SELECT - col2 * - - 40 * + col1 AS col1 FROM tab1
;

CREATE VIRTUAL VIEW V722 AS SELECT ( + + 57 ) * - 34 FROM tab2
;

CREATE VIRTUAL VIEW V723 AS SELECT - + col0 FROM tab0 WHERE NULL IS NOT NULL
;

CREATE VIRTUAL VIEW V724 AS SELECT col1, - ( ( + col1 ) ) FROM tab2
;

CREATE VIRTUAL VIEW V725 AS SELECT + col1 FROM tab2 WHERE 12 IS NOT NULL
;

CREATE VIRTUAL VIEW V726 AS SELECT DISTINCT - col2 * - ( + col0 ) + + col0 FROM tab2 cor0
;

CREATE VIRTUAL VIEW V727 AS SELECT ALL col1 AS col1 FROM tab1 WHERE NOT + 76 + + + 8 > - col1
;

CREATE VIRTUAL VIEW V728 AS SELECT + col2 + + 89 + ( - - 64 ) * + 92 * + col1 AS col0 FROM tab2
;

CREATE VIRTUAL VIEW V729 AS SELECT 80 * - - 85 + - + 14, + col0 AS col0 FROM tab1
;

CREATE VIRTUAL VIEW V730 AS SELECT * FROM tab2 AS cor0 WHERE 62 IS NULL
;

CREATE VIRTUAL VIEW V731 AS SELECT DISTINCT + + 86 - - + 96 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V732 AS SELECT DISTINCT * FROM tab1 WHERE + 1 IS NULL
;

CREATE VIRTUAL VIEW V733 AS SELECT + 25, 63 AS col1 FROM tab1
;

CREATE VIRTUAL VIEW V734 AS SELECT ALL col2, + 40 * - 7 * col0 FROM tab1
;

CREATE VIRTUAL VIEW V735 AS SELECT DISTINCT * FROM tab0 WHERE NOT ( - col2 ) IN ( col0 )
;

CREATE VIRTUAL VIEW V736 AS SELECT * FROM tab1 AS cor0 WHERE NOT + 5 - col0 + col1 * + col0 IS NOT NULL
;

CREATE VIRTUAL VIEW V737 AS SELECT DISTINCT * FROM tab0 AS cor0 WHERE + 91 > NULL
;

CREATE VIRTUAL VIEW V738 AS SELECT - 31 * - col0 + - col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V739 AS SELECT * FROM tab2 AS cor0 WHERE NOT 32 BETWEEN NULL AND - 53
;

CREATE VIRTUAL VIEW V740 AS SELECT col1 AS col1, col2 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V741 AS SELECT ALL + col0 FROM tab0 AS cor0 WHERE NOT ( - - col2 ) >= + col0
;

CREATE VIRTUAL VIEW V742 AS SELECT * FROM tab2 AS cor0 WHERE NOT col0 = + col0 * col0 + + + col2
;

CREATE VIRTUAL VIEW V743 AS SELECT col1 * - - 43 FROM tab0
;

CREATE VIRTUAL VIEW V744 AS SELECT ( - 96 ) FROM tab1 WHERE + + col1 NOT IN ( - - col2 + col2, col0, col1, + 68 + col1, - + col0 / + 14 * - col1 + + col1 * + + col1 * - ( ( + 54 ) ) )
;

CREATE VIRTUAL VIEW V745 AS SELECT * FROM tab1 WHERE + - 45 IS NULL
;

CREATE VIRTUAL VIEW V746 AS SELECT - - 8 * - col0 + - col0 + + 0 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V747 AS SELECT DISTINCT * FROM tab1 AS cor0 WHERE NOT ( NULL ) NOT BETWEEN - 96 AND - + ( - + col1 )
;

CREATE VIRTUAL VIEW V748 AS SELECT col0 + + - col0 + + col2 FROM tab0 WHERE NULL IS NULL
;

CREATE VIRTUAL VIEW V749 AS SELECT ALL - col1 + - 12 + - - 65 + - + 39 * + 18 + - col0 AS col2 FROM tab1 WHERE ( NULL NOT BETWEEN NULL AND col1 * - - col2 )
;

CREATE VIRTUAL VIEW V750 AS SELECT + 68 + 83 * - col2 * + col2 + + - 6 - col1 AS col2, ( - col0 ) FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V751 AS SELECT ALL + col0, col1 AS col1 FROM tab0 cor0
;

CREATE VIRTUAL VIEW V752 AS SELECT 30 + - 16 + 49 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V753 AS SELECT DISTINCT col2 * - + 17 AS col1 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V754 AS SELECT DISTINCT 58 * - col0 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V755 AS SELECT 29 FROM tab2 AS cor0 WHERE NOT - col0 IS NULL
;

CREATE VIRTUAL VIEW V756 AS SELECT ALL - col2 * + 22 * - 58 * + col1 FROM tab2
;

CREATE VIRTUAL VIEW V757 AS SELECT DISTINCT col2 FROM tab2 WHERE 78 >= NULL
;

CREATE VIRTUAL VIEW V758 AS SELECT + 64 * col1 * + col0 AS col2 FROM tab0
;

CREATE VIRTUAL VIEW V759 AS SELECT 41 * + - col2 AS col1 FROM tab2
;

CREATE VIRTUAL VIEW V760 AS SELECT - col1 AS col2, 93 + - 51 FROM tab1
;

CREATE VIRTUAL VIEW V761 AS SELECT ALL col2 AS col1 FROM tab0 WHERE NULL IS NOT NULL
;

CREATE VIRTUAL VIEW V762 AS SELECT ALL 9 FROM tab0 cor0
;

CREATE VIRTUAL VIEW V763 AS SELECT ALL * FROM tab1 AS cor0 WHERE NULL < col1 * + + col2 * + - col1
;

CREATE VIRTUAL VIEW V764 AS SELECT 1 - CAST(SUM ( ALL - col2 ) AS INTEGER) FROM tab2 AS cor0 WHERE NULL IS NOT NULL
;

CREATE VIRTUAL VIEW V765 AS SELECT - ( - ( - + col1 ) ) FROM tab2 cor0
;

CREATE VIRTUAL VIEW V766 AS SELECT - col2, col2 AS col1 FROM tab2 AS cor0 WHERE + col0 * - col2 IS NOT NULL
;

CREATE VIRTUAL VIEW V767 AS SELECT DISTINCT + col0 + - ( - col0 ) * + 46 * col2 AS col0 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V768 AS SELECT ALL + col0 * - col0 + + - col2 * col1 AS col1 FROM tab1
;

CREATE VIRTUAL VIEW V769 AS SELECT - ( - 77 ) FROM tab0
;

CREATE VIRTUAL VIEW V770 AS SELECT + col1 AS col0 FROM tab0 WHERE ( NOT 73 / + - 94 IS NULL )
;

CREATE VIRTUAL VIEW V771 AS SELECT DISTINCT * FROM tab0 AS cor0 WHERE ( - col1 ) IS NOT NULL
;

CREATE VIRTUAL VIEW V772 AS SELECT + col0 * 95 - + - col1 + - col0 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V773 AS SELECT 77 FROM tab0 WHERE - 38 IS NOT NULL
;

CREATE VIRTUAL VIEW V774 AS SELECT ALL - 87 * + col1 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V775 AS SELECT DISTINCT + - 24 * - - col1 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V776 AS SELECT + col1 + - 5 AS col2 FROM tab1 AS cor0 WHERE NOT + col2 * col1 IS NOT NULL
;

CREATE VIRTUAL VIEW V777 AS SELECT + - ( 39 ) FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V778 AS SELECT + 10 * col0 + + col2 AS col0 FROM tab2 WHERE NOT NULL IS NULL
;

CREATE VIRTUAL VIEW V779 AS SELECT DISTINCT * FROM tab0 WHERE 98 * col1 = col2 * + - col2
;

CREATE VIRTUAL VIEW V780 AS SELECT col0, + 3 AS col1 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V781 AS SELECT * FROM tab1 WHERE NOT ( NOT - 75 - col0 / + col0 NOT BETWEEN NULL AND NULL )
;

CREATE VIRTUAL VIEW V782 AS SELECT DISTINCT - - 84 + 53 AS col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V783 AS SELECT - ( ( + col0 ) ) AS col0 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V784 AS SELECT ALL - 73 + + 21 AS col2, + ( - col0 ) + + col0 * col1 AS col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V785 AS SELECT DISTINCT + ( - 93 ) + - 16 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V786 AS SELECT * FROM tab1 WHERE 93 = 34
;

CREATE VIRTUAL VIEW V787 AS SELECT ALL 77, col2 AS col2 FROM tab0
;

CREATE VIRTUAL VIEW V788 AS SELECT + + 16 FROM tab0 cor0 WHERE ( NULL ) IS NULL
;

CREATE VIRTUAL VIEW V789 AS SELECT DISTINCT + + 15 * 48 + col0 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V790 AS SELECT DISTINCT - col0 + - ( - col0 ) FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V791 AS SELECT DISTINCT * FROM tab0 AS cor0 WHERE 91 * + col0 IS NULL
;

CREATE VIRTUAL VIEW V792 AS SELECT DISTINCT - - 95 / - - col0 FROM tab0 WHERE NULL BETWEEN - - col1 AND - col1 * - col1 + + col1 + - col0 + + col1 + - 56 * + col1 * - col2
;

CREATE VIRTUAL VIEW V793 AS SELECT DISTINCT * FROM tab0 WHERE NOT col2 <= + 36
;

CREATE VIRTUAL VIEW V794 AS SELECT ( + + 2 ) AS col0 FROM tab2
;

CREATE VIRTUAL VIEW V795 AS SELECT ALL * FROM tab0 AS cor0 WHERE - col1 * + 81 NOT BETWEEN NULL AND - col1 * + 35 * - col1 * + col2
;

CREATE VIRTUAL VIEW V796 AS SELECT - - ( + + 94 ) AS col0 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V797 AS SELECT DISTINCT + + 2 AS col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V798 AS SELECT * FROM tab1 AS cor0 WHERE NOT + col0 > NULL
;

CREATE VIRTUAL VIEW V799 AS SELECT 28 AS col1, 35 * + col2 FROM tab1
;

CREATE VIRTUAL VIEW V800 AS SELECT ALL 37 * - 10 FROM tab2
;

CREATE VIRTUAL VIEW V801 AS SELECT + col2 AS col0 FROM tab1 WHERE NOT NULL BETWEEN - col1 + + 71 - + col2 AND + col2
;

CREATE VIRTUAL VIEW V802 AS SELECT ALL + 45 * - + col0 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V803 AS SELECT ( col1 ) * - col1 + col2 + + + col0 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V804 AS SELECT * FROM tab1 AS cor0 WHERE NOT col0 + + + 15 IS NULL
;

CREATE VIRTUAL VIEW V805 AS SELECT - + col0 + col1 * col0 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V806 AS SELECT * FROM tab2 AS cor0 WHERE NULL >= 61
;

CREATE VIRTUAL VIEW V807 AS SELECT + 96 * - - col1 * + 88 AS col0 FROM tab0
;

CREATE VIRTUAL VIEW V808 AS SELECT DISTINCT - 98 - + - col2 * col2 FROM tab0
;

CREATE VIRTUAL VIEW V809 AS SELECT + 51 * - col1 * 84 - - col0 AS col1 FROM tab0
;

CREATE VIRTUAL VIEW V810 AS SELECT DISTINCT 42 * + ( + col0 ) AS col0 FROM tab1
;

CREATE VIRTUAL VIEW V811 AS SELECT DISTINCT * FROM tab0 WHERE NOT 66 / col0 + + col2 / - 77 * - ( ( + - col2 ) ) * - - col0 + + col0 * 47 * - + col0 IS NOT NULL
;

CREATE VIRTUAL VIEW V812 AS SELECT 44 * col0 - col2 - 90 + 66 FROM tab0
;

CREATE VIRTUAL VIEW V813 AS SELECT + 4 FROM tab0 AS cor0 WHERE + col0 IS NULL
;

CREATE VIRTUAL VIEW V814 AS SELECT ALL + 24 * + 29 FROM tab1 AS cor0 WHERE ( NULL ) = NULL
;

CREATE VIRTUAL VIEW V815 AS SELECT + col0 AS col1, col0 FROM tab0
;

CREATE VIRTUAL VIEW V816 AS SELECT * FROM tab0 cor0 WHERE NOT 43 * - + col0 * - - col0 + + col1 + + col1 NOT IN ( col0 )
;

CREATE VIRTUAL VIEW V817 AS SELECT - - 40 AS col1 FROM tab2 AS cor0 WHERE NOT ( NULL ) IS NOT NULL
;

CREATE VIRTUAL VIEW V818 AS SELECT + col0 AS col0 FROM tab2 AS cor0 WHERE NOT NULL <= 79 * + 23 * + 41
;

CREATE VIRTUAL VIEW V819 AS SELECT * FROM tab2 WHERE NOT - 85 BETWEEN NULL AND NULL
;

CREATE VIRTUAL VIEW V820 AS SELECT 1 * + ( col0 ) AS col0 FROM tab2
;

CREATE VIRTUAL VIEW V821 AS SELECT DISTINCT * FROM tab2 WHERE - + col2 + - col0 IS NOT NULL
;

CREATE VIRTUAL VIEW V822 AS SELECT DISTINCT - + col1 AS col0 FROM tab0 WHERE - 52 - - 78 + col1 NOT BETWEEN - - 81 * - col2 AND + ( + 54 )
;

CREATE VIRTUAL VIEW V823 AS SELECT ALL - ( - 63 ) FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V824 AS SELECT ALL + col1 + - 61 + col1 AS col1 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V825 AS SELECT DISTINCT + 29 * col1 + 76 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V826 AS SELECT DISTINCT * FROM tab1 WHERE NOT NULL >= + 5 + - col2
;

CREATE VIRTUAL VIEW V827 AS SELECT ALL + col2, col1 AS col1 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V828 AS SELECT 37 + - - ( col2 ) * - + col2 AS col1 FROM tab2 cor0
;

CREATE VIRTUAL VIEW V829 AS SELECT - - ( + 25 ) + + 54 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V830 AS SELECT ALL * FROM tab0 WHERE NULL > + col2 * + col1
;

CREATE VIRTUAL VIEW V831 AS SELECT col1 * + + col0 AS col2 FROM tab2
;

CREATE VIRTUAL VIEW V832 AS SELECT ALL col0 + col0 * - - col1 AS col0 FROM tab0
;

CREATE VIRTUAL VIEW V833 AS SELECT DISTINCT * FROM tab0 WHERE NOT ( col1 ) IS NULL
;

CREATE VIRTUAL VIEW V834 AS SELECT DISTINCT * FROM tab0 AS cor0 WHERE NOT col2 + - 60 IS NOT NULL
;

CREATE VIRTUAL VIEW V835 AS SELECT ALL + ( - 36 ) FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V836 AS SELECT ALL * FROM tab2 AS cor0 WHERE NOT 29 + - + col1 IS NOT NULL
;

CREATE VIRTUAL VIEW V837 AS SELECT col1 * + 60 * + - 82 AS col1 FROM tab1
;

CREATE VIRTUAL VIEW V838 AS SELECT + col2 AS col1, + ( - + col0 ) * 55 FROM tab0
;

CREATE VIRTUAL VIEW V839 AS SELECT ALL - col0 + - ( - col1 ) AS col2 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V840 AS SELECT col1 + + - col0 AS col0 FROM tab1
;

CREATE VIRTUAL VIEW V841 AS SELECT col2 * - 65 FROM tab2
;

CREATE VIRTUAL VIEW V842 AS SELECT * FROM tab0 AS cor0 WHERE ( NULL ) BETWEEN NULL AND - col0
;

CREATE VIRTUAL VIEW V843 AS SELECT + 56 * - 25 * + + col0 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V844 AS SELECT DISTINCT col1 - + + col0 AS col1 FROM tab1
;

CREATE VIRTUAL VIEW V845 AS SELECT col0 * + 43 - + - col0 * + col2 FROM tab2
;

CREATE VIRTUAL VIEW V846 AS SELECT * FROM tab2 WHERE + col1 + + + col2 * + col2 IS NULL
;

CREATE VIRTUAL VIEW V847 AS SELECT * FROM tab1 WHERE NOT + ( 51 ) > ( NULL )
;

CREATE VIRTUAL VIEW V848 AS SELECT DISTINCT 70 AS col0 FROM tab2
;

CREATE VIRTUAL VIEW V849 AS SELECT DISTINCT * FROM tab1 WHERE NOT 52 / + 11 IS NOT NULL
;

CREATE VIRTUAL VIEW V850 AS SELECT ALL * FROM tab1 AS cor0 WHERE NOT ( + col2 IS NOT NULL )
;

CREATE VIRTUAL VIEW V851 AS SELECT + - col1 * - + ( col1 ) AS col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V852 AS SELECT DISTINCT - col1 * - - 78 AS col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V853 AS SELECT ALL * FROM tab0 AS cor0 WHERE col1 > ( - - 91 )
;

CREATE VIRTUAL VIEW V854 AS SELECT + col2 AS col0 FROM tab2 AS cor0 WHERE NOT NULL BETWEEN NULL AND col2
;

CREATE VIRTUAL VIEW V855 AS SELECT col2, + 12 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V856 AS SELECT DISTINCT - - 8 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V857 AS SELECT ALL * FROM tab0 WHERE + col0 < + col0 * + col0
;

CREATE VIRTUAL VIEW V858 AS SELECT ALL * FROM tab0 WHERE - 39 + col0 IS NULL
;

CREATE VIRTUAL VIEW V859 AS SELECT * FROM tab2 WHERE - col2 * + + col1 < NULL
;

CREATE VIRTUAL VIEW V860 AS SELECT col1 FROM tab0 AS cor0 WHERE NULL IS NOT NULL
;

CREATE VIRTUAL VIEW V861 AS SELECT DISTINCT col1 + 39 AS col2 FROM tab0
;

CREATE VIRTUAL VIEW V862 AS SELECT + col2 + - - 37 AS col1 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V863 AS SELECT ALL col0 - - + col1 + + - col2 * - col1 FROM tab0
;

CREATE VIRTUAL VIEW V864 AS SELECT DISTINCT + 2 + 79 AS col0 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V865 AS SELECT DISTINCT ( - col1 ) * - 12 AS col2 FROM tab2
;

CREATE VIRTUAL VIEW V866 AS SELECT + col2 * + 17 * - - col1 FROM tab1
;

CREATE VIRTUAL VIEW V867 AS SELECT col2, + col1 FROM tab2
;

CREATE VIRTUAL VIEW V868 AS SELECT ALL + col0 - + col2 AS col2, col2 AS col2 FROM tab0
;

CREATE VIRTUAL VIEW V869 AS SELECT + + 73 * + + 47 FROM tab2 cor0
;

CREATE VIRTUAL VIEW V870 AS SELECT - 1 * + col1, + col2 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V871 AS SELECT - 7 AS col0, col1 AS col2 FROM tab2
;

CREATE VIRTUAL VIEW V872 AS SELECT - 97, col0 AS col0 FROM tab2
;

CREATE VIRTUAL VIEW V873 AS SELECT ALL - col0 * + - col2 AS col2 FROM tab2
;

CREATE VIRTUAL VIEW V874 AS SELECT * FROM tab1 WHERE NOT 85 <> - col0
;

CREATE VIRTUAL VIEW V875 AS SELECT DISTINCT * FROM tab2 WHERE ( NOT NULL IS NULL )
;

CREATE VIRTUAL VIEW V876 AS SELECT DISTINCT col1 AS col0 FROM tab0 AS cor0 WHERE NOT + col2 + - 80 IS NULL
;

CREATE VIRTUAL VIEW V877 AS SELECT col2 * - 42 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V878 AS SELECT - col0 + 78 AS col2 FROM tab0
;

CREATE VIRTUAL VIEW V879 AS SELECT DISTINCT + 11 * - col1 FROM tab2
;

CREATE VIRTUAL VIEW V880 AS SELECT col2 + col1 * - 43 FROM tab0
;

CREATE VIRTUAL VIEW V881 AS SELECT * FROM tab0 WHERE NOT ( + 59 ) BETWEEN NULL AND NULL
;

CREATE VIRTUAL VIEW V882 AS SELECT DISTINCT * FROM tab0 WHERE NOT + 76 IS NULL
;

CREATE VIRTUAL VIEW V883 AS SELECT - 35 * ( col0 * + col0 ) FROM tab2
;

CREATE VIRTUAL VIEW V884 AS SELECT - 62 * + col0 AS col1 FROM tab2 WHERE NOT NULL IS NULL
;

CREATE VIRTUAL VIEW V885 AS SELECT * FROM tab2 WHERE 65 IN ( - 96 )
;

CREATE VIRTUAL VIEW V886 AS SELECT DISTINCT 34 + 24 AS col1 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V887 AS SELECT ALL - 83 * - 0 - col1 AS col0 FROM tab1
;

CREATE VIRTUAL VIEW V888 AS SELECT - 28 AS col0 FROM tab2 AS cor0 WHERE NOT NULL IS NOT NULL
;

CREATE VIRTUAL VIEW V889 AS SELECT - - col2 * - 73 AS col2 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V890 AS SELECT * FROM tab2 AS cor0 WHERE NOT NULL = 35
;

CREATE VIRTUAL VIEW V891 AS SELECT * FROM tab2 AS cor0 WHERE NOT NULL BETWEEN ( col0 * - col1 ) AND + col0
;

CREATE VIRTUAL VIEW V892 AS SELECT * FROM tab0 WHERE NOT + col1 >= ( + 56 )
;

CREATE VIRTUAL VIEW V893 AS SELECT col2 * - col1 FROM tab0 WHERE NOT col0 NOT IN ( col0 * - col1 + + 46 * col0 )
;

CREATE VIRTUAL VIEW V894 AS SELECT * FROM tab0 AS cor0 WHERE NOT ( - 85 ) <= - col0
;

CREATE VIRTUAL VIEW V895 AS SELECT DISTINCT * FROM tab0 cor0 WHERE ( 37 ) + 44 IS NULL
;

CREATE VIRTUAL VIEW V896 AS SELECT ALL 1 FROM tab1 AS cor0 WHERE NULL IS NOT NULL
;

CREATE VIRTUAL VIEW V897 AS SELECT * FROM tab0 AS cor0 WHERE NULL <= col2 * + col1
;

CREATE VIRTUAL VIEW V898 AS SELECT DISTINCT + col1 FROM tab1 AS cor0 WHERE col1 NOT BETWEEN - - col1 AND NULL
;

CREATE VIRTUAL VIEW V899 AS SELECT DISTINCT col2 FROM tab0 AS cor0 WHERE NOT - col2 IN ( + 49 + + col0 )
;

CREATE VIRTUAL VIEW V900 AS SELECT * FROM tab1 WHERE col0 > + - col1
;

CREATE VIRTUAL VIEW V901 AS SELECT ALL * FROM tab1 WHERE NOT - + col0 * - col1 * + 7 >= ( NULL )
;

CREATE VIRTUAL VIEW V902 AS SELECT col1 FROM tab2 WHERE ( + 92 ) IS NOT NULL
;

CREATE VIRTUAL VIEW V903 AS SELECT ALL col0 - + ( + col1 ) FROM tab1
;

CREATE VIRTUAL VIEW V904 AS SELECT ALL * FROM tab0 AS cor0 WHERE ( - 71 ) IS NULL
;

CREATE VIRTUAL VIEW V905 AS SELECT DISTINCT - 53 + - ( + 59 ) FROM tab0 cor0
;

CREATE VIRTUAL VIEW V906 AS SELECT ALL * FROM tab2 AS cor0 WHERE NOT ( + col2 ) IS NOT NULL
;

CREATE VIRTUAL VIEW V907 AS SELECT ALL * FROM tab0 AS cor0 WHERE ( NULL ) NOT IN ( + col0 + + + col1 )
;

CREATE VIRTUAL VIEW V908 AS SELECT ALL * FROM tab1 cor0 WHERE - 1 IS NOT NULL
;

CREATE VIRTUAL VIEW V909 AS SELECT DISTINCT * FROM tab2 AS cor0 WHERE NOT - 82 NOT BETWEEN - col0 AND ( NULL )
;

CREATE VIRTUAL VIEW V910 AS SELECT * FROM tab2 AS cor0 WHERE NOT col2 * + - col1 BETWEEN NULL AND col1 - + + 27 + 36
;

CREATE VIRTUAL VIEW V911 AS SELECT + ( - ( 87 ) ) * - - 11 - ( 95 ) + col1 * 4 * col2 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V912 AS SELECT ALL - col0 AS col0, 28 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V913 AS SELECT col0 AS col0 FROM tab2 AS cor0 WHERE NOT - ( - col2 ) * - + 4 - - col1 IS NOT NULL
;

CREATE VIRTUAL VIEW V914 AS SELECT + col2, - col0 AS col0 FROM tab1
;

CREATE VIRTUAL VIEW V915 AS SELECT * FROM tab2, tab1 AS cor0 WHERE ( 7 ) > NULL
;

CREATE VIRTUAL VIEW V916 AS SELECT ALL * FROM tab0 WHERE col0 IN ( - + 46 * + 58 )
;

CREATE VIRTUAL VIEW V917 AS SELECT - col1, + col0 * - col1 + + ( + - col1 ) AS col2 FROM tab0
;

CREATE VIRTUAL VIEW V918 AS SELECT DISTINCT col1 AS col2, - col0 FROM tab1
;

CREATE VIRTUAL VIEW V919 AS SELECT * FROM tab0 AS cor0 WHERE NOT ( NULL ) NOT BETWEEN NULL AND + - col1
;

CREATE VIRTUAL VIEW V920 AS SELECT * FROM tab0 AS cor0 WHERE ( NULL ) BETWEEN col0 AND ( NULL )
;

CREATE VIRTUAL VIEW V921 AS SELECT ALL 26 + + col2 FROM tab1 AS cor0 WHERE NOT NULL = NULL
;

CREATE VIRTUAL VIEW V922 AS SELECT DISTINCT ( + - col0 ) AS col0 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V923 AS SELECT DISTINCT - 80 + + 19 + - + col0 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V924 AS SELECT col0 FROM tab0 AS cor0 WHERE col0 * col0 NOT BETWEEN NULL AND + 15
;

CREATE VIRTUAL VIEW V925 AS SELECT ALL + col0 * + + 77 + col0 AS col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V926 AS SELECT * FROM tab1 AS cor0 WHERE - 99 * + col1 IN ( - - col2 )
;

CREATE VIRTUAL VIEW V927 AS SELECT col1 + - ( 81 ) FROM tab1 cor0
;

CREATE VIRTUAL VIEW V928 AS SELECT * FROM tab2 AS cor0 WHERE 79 IS NOT NULL
;

CREATE VIRTUAL VIEW V929 AS SELECT ALL col2 + + col1 + - col2 AS col1, col0 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V930 AS SELECT * FROM tab0 WHERE + - col0 + col2 IS NULL
;

CREATE VIRTUAL VIEW V931 AS SELECT col2 AS col1, + col2 * + 21 + - - 85 * - col2 FROM tab0
;

CREATE VIRTUAL VIEW V932 AS SELECT DISTINCT + col1 AS col2, 69 AS col2 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V933 AS SELECT DISTINCT - 75 * - - col0 FROM tab0 AS cor0
;

CREATE VIRTUAL VIEW V934 AS SELECT 31 FROM tab2 AS cor0 WHERE NOT + col0 = ( col2 )
;

CREATE VIRTUAL VIEW V935 AS SELECT ALL 67 AS col0 FROM tab0 AS cor0 WHERE NOT ( NULL ) IS NULL
;

CREATE VIRTUAL VIEW V936 AS SELECT * FROM tab2 WHERE NOT col2 + + 53 IN ( 78 ) AND NOT ( col2 + + 10 IS NULL )
;

CREATE VIRTUAL VIEW V937 AS SELECT 4 * + col1 AS col1 FROM tab0
;

CREATE VIRTUAL VIEW V938 AS SELECT ALL * FROM tab1 WHERE NOT ( - + 13 * 36 + - col1 / - col2 * 98 + col0 * - col2 ) IS NOT NULL
;

CREATE VIRTUAL VIEW V939 AS SELECT DISTINCT 34 + - col0 * - - ( - col0 ) FROM tab1
;

CREATE VIRTUAL VIEW V940 AS SELECT col2 + - + 87 AS col2, - col0 FROM tab1
;

CREATE VIRTUAL VIEW V941 AS SELECT ALL + col1 * - - col1 FROM tab0
;

CREATE VIRTUAL VIEW V942 AS SELECT ALL - 62 + - - col1 FROM tab2 cor0
;

CREATE VIRTUAL VIEW V943 AS SELECT col1 FROM tab2 AS cor0 WHERE NULL IS NOT NULL
;

CREATE VIRTUAL VIEW V944 AS SELECT * FROM tab1 WHERE ( col2 ) * + col0 IS NULL
;

CREATE VIRTUAL VIEW V945 AS SELECT DISTINCT * FROM tab0 WHERE NOT ( 60 >= - 57 )
;

CREATE VIRTUAL VIEW V946 AS SELECT + 26 - + ( - col0 ) AS col2 FROM tab2 cor0 WHERE NOT col0 IS NULL
;

CREATE VIRTUAL VIEW V947 AS SELECT DISTINCT col1 * + - 38 + - col2 AS col2 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V948 AS SELECT - 21 * + 1 FROM tab1 cor0
;

CREATE VIRTUAL VIEW V949 AS SELECT col1 * + - 31 * + 21 * + col2 * + col0 + col0 AS col1 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V950 AS SELECT ALL col0, 17 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V951 AS SELECT + col2 * - - 37 FROM tab2
;

CREATE VIRTUAL VIEW V952 AS SELECT * FROM tab0 WHERE NOT NULL NOT BETWEEN + - col1 AND - col0 * col1 + 81 + col0 / - col1
;

CREATE VIRTUAL VIEW V953 AS SELECT + col1 AS col0 FROM tab2 WHERE NOT - 97 / + + col2 - + col1 > NULL
;

CREATE VIRTUAL VIEW V954 AS SELECT ALL - - col0 FROM tab1 WHERE NOT NULL BETWEEN - 3 * - col0 + - - ( - + 93 ) AND - + col0
;

CREATE VIRTUAL VIEW V955 AS SELECT DISTINCT * FROM tab1 WHERE + col1 / + col2 * col0 IS NULL
;

CREATE VIRTUAL VIEW V956 AS SELECT DISTINCT * FROM tab0 WHERE NOT ( - 35 IS NOT NULL )
;

CREATE VIRTUAL VIEW V957 AS SELECT ALL - col1 AS col1, 39 FROM tab2
;

CREATE VIRTUAL VIEW V958 AS SELECT - + 40 + - + 76 AS col2 FROM tab2 AS cor0
;

CREATE VIRTUAL VIEW V959 AS SELECT 80 + 65 FROM tab1 AS cor0
;

CREATE VIRTUAL VIEW V960 AS SELECT * FROM tab0 AS cor0 WHERE - col2 = - ( - - col1 )
;

CREATE VIRTUAL VIEW V961 AS SELECT ALL - 61 + col2 AS col1 FROM tab2
;

CREATE VIRTUAL VIEW V962 AS SELECT + col1 * + 49 AS col1 FROM tab1
;

CREATE VIRTUAL VIEW V963 AS SELECT + 68 * - 66 * - - col2 AS col0 FROM tab0
;

CREATE VIRTUAL VIEW V964 AS SELECT DISTINCT 94, + col2 FROM tab0
;

CREATE VIRTUAL VIEW V965 AS SELECT ALL + 22 FROM tab0 WHERE - + col0 IS NULL
;

