apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-kubernetes-ingress
data:
  syslog-server: "address:stdout, format: raw, facility:daemon"
  frontend-config-snippet: |
     http-request set-header Follower-Prefix %[path,field(3,/)] if { path_beg -i /streams/ }
     use_backend skip_stream if { path_beg -i /streams/ }
     use_backend skip_control if { path_beg -i /control/ }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haproxy-kubernetes-ingress
spec:
  ingressClassName: haproxy
  rules:
    - http:
        paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: rhn-web
              port:
                number: 3031
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: rhn-www
              port:
                number: 80
