apiVersion: v1
kind: Service
metadata:
  name: rhn-pg
  labels:
    app.kubernetes.io/name: rhn-pg
spec:
  selector:
    app.kubernetes.io/name: rhn-pg
  ports:
    - port: 5432
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhn-pg
  labels:
    app.kubernetes.io/name: rhn-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rhn-pg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rhn-pg
    spec:
      containers:
      - name: rhn-pg
        image: localhost:5000/db
        ports:
        - containerPort: 5432
