apiVersion: v1
kind: Service
metadata:
  name: rhn-skip
  labels:
    app.kubernetes.io/name: rhn-skip
spec:
  ports:
    - port: 8080
      name: streaming
    - port: 8081
      name: control
  clusterIP: None
  selector:
    app.kubernetes.io/name: rhn-skip
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rhn-skip
  labels:
    app.kubernetes.io/name: rhn-skip
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rhn-skip
  serviceName: rhn-skip
  replicas: 4
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rhn-skip
    spec:
      containers:
      - name: rhn-skip
        image: localhost:5000/reactive-service
        command:
        - bash
        - "-c"
        - |
          set -ex
          # use Kubernetes pod index as ID:
          # - index 0 is leader
          # - index >= 1 is follower, using that number in resource prefix
          [[ $HOSTNAME =~ -([0-9]+)$ ]] || exit 1
          id=${BASH_REMATCH[1]}
          if [[ $id -eq 0 ]]; then
            export SKIP_LEADER=true
          else
            export SKIP_FOLLOWER=true
            export SKIP_RESOURCE_PREFIX=follower$id
            export SKIP_LEADER_HOST=rhn-skip-0.rhn-skip.default.svc.cluster.local
          fi
          npm start
        ports:
        - name: streaming
          containerPort: 8080
        - name: control
          containerPort: 8081
        env:
        - name: PG_HOST
          value: "rhn-pg.default.svc.cluster.local"
        - name: PG_PORT
          value: "5432"
        readinessProbe:
          exec:
            command:
            - wget
            - "--spider"
            - http://localhost:8081/v1/healthcheck
          initialDelaySeconds: 5
          periodSeconds: 5
# Headless services giving names to followers, binding on selector
# `statefulset.kubernetes.io/pod-name`
# This is just to give a service identifier for haproxy ingress controller to
# use to distribute streaming requests to the proper followers.

# These headless services need to be created for each pod of the stateful set;
# i.e. it is required to define services rhn-skip-ingress-X for all X from 0 to
# <number of rhn-skip replicas>.  It is recommended to create enough such
# headless services to  support the high end of expected follower instances;
# then, horizontal scaling just requires changing the number of replicas in the
# rhn-skip StatefulSet.
---
apiVersion: v1
kind: Service
metadata:
  name: rhn-skip-ingress-0
spec:
  clusterIP: None
  ports:
    - name: streaming
      port: 8080
      targetPort: 8080
    - name: control
      port: 8081
      targetPort: 8081
  selector:
    statefulset.kubernetes.io/pod-name: rhn-skip-0
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rhn-skip-ingress-1
spec:
  clusterIP: None
  ports:
    - name: streaming
      port: 8080
      targetPort: 8080
    - name: control
      port: 8081
      targetPort: 8081
  selector:
    statefulset.kubernetes.io/pod-name: rhn-skip-1
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rhn-skip-ingress-2
spec:
  clusterIP: None
  ports:
    - name: streaming
      port: 8080
      targetPort: 8080
    - name: control
      port: 8081
      targetPort: 8081
  selector:
    statefulset.kubernetes.io/pod-name: rhn-skip-2
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rhn-skip-ingress-3
spec:
  clusterIP: None
  ports:
    - name: streaming
      port: 8080
      targetPort: 8080
    - name: control
      port: 8081
      targetPort: 8081
  selector:
    statefulset.kubernetes.io/pod-name: rhn-skip-3
  type: ClusterIP
