apiVersion: v1
kind: Service
metadata:
  name: rhn-skip
  labels:
    app.kubernetes.io/name: rhn-skip
  annotations:
    haproxy.org/backend-config-snippet: |
      http-request set-path /v1%[path,regsub(^/control/,/)]
spec:
  ports:
    - port: 8080
      name: streaming
    - port: 8081
      name: control
  selector:
    app.kubernetes.io/name: rhn-skip
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhn-skip
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rhn-skip
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rhn-skip
    spec:
      containers:
      - name: rhn-skip
        image: localhost:5000/reactive-service
        ports:
        - name: streaming
          containerPort: 8080
        - name: control
          containerPort: 8081
        env:
        - name: PG_HOST
          value: "rhn-pg.default.svc.cluster.local"
        - name: PG_PORT
          value: "5432"
        readinessProbe:
          exec:
            command:
            - wget
            - "--spider"
            - http://localhost:8081/v1/healthcheck
          initialDelaySeconds: 1
          periodSeconds: 2
